export interface ChapterWebtoonCut {
  cutNumber: number;
  title: string;
  image: string;
  badge: string;
  badgeType: 'safe' | 'penalty' | 'caution' | 'info';
  situation: string;
  parkyDialogue: string;
  verdict: string;
  penaltyText?: string;
  keyPoint: string;
  article: string;
}

export interface ChapterWebtoon {
  chapterId: string;
  chapterNumber: string;
  title: string;
  subtitle: string;
  coverImage: string;
  totalCuts: number;
  cuts: ChapterWebtoonCut[];
}

export const CHAPTER_WEBTOONS: Record<string, ChapterWebtoon> = {
  'ch-1': {
    chapterId: 'ch-1',
    chapterNumber: '제1장',
    title: '코스 탐험과 기본 규정',
    subtitle: '9홀 33타 공인 기준과 5대 코스 구역의 비밀',
    coverImage: '/mascot/master_cuts/ch-1_cover.jpg',
    totalCuts: 3,
    cuts: [
      {
        cutNumber: 1,
        title: '파크골프의 정석! 9홀 Par 33 공인 규격',
        image: '/mascot/master_cuts/ch-1_cut1.jpg',
        badge: '공인 규격',
        badgeType: 'info',
        situation: '파크골프는 일반 골프와 홀수 및 기준 타수가 어떻게 다를까요?',
        parkyDialogue: '안녕하세요! 파크골프 올인원 마스코트 파키예요! 파크골프 공인 규격은 9홀 기준 총 33타(Par 33)가 표준이랍니다! Par 3 4개, Par 4 4개, Par 5 1개로 알차게 구성되어 있어요!',
        verdict: '9홀 기준 기준타수 33타 (18홀 66타)',
        keyPoint: '전체 거리는 9홀 약 660m 내외로 남녀노소 누구나 걷기 좋은 도심 속 친환경 코스입니다.',
        article: '제1장 제2조 (코스의 구성 및 구역)',
      },
      {
        cutNumber: 2,
        title: '티잉그라운드(티박스) 매트 구역의 비밀',
        image: '/mascot/master_cuts/ch-1_cut2.jpg',
        badge: '출발 구역',
        badgeType: 'caution',
        situation: '티샷을 날리는 매트는 어디까지가 정규 구역일까요?',
        parkyDialogue: '티박스는 각 홀의 출발점이에요! 인조잔디 매트 또는 양측 티마커 전면선 뒤쪽 2클럽 이내 직사각형 구역에서만 티샷이 가능해요! 두 발이 모두 나가면 2벌타를 받으니 꼭 주의하세요!',
        verdict: '티마커 전면선 ~ 후방 2클럽 직사각형',
        penaltyText: '두 발 모두 매트 이탈 시 2벌타',
        keyPoint: '티샷 시 최소 한 발의 일부는 반드시 매트 안에 닿아 있어야 합니다.',
        article: '제1장 제3조 (티잉그라운드) & 제31조',
      },
      {
        cutNumber: 3,
        title: '5대 코스 구역과 OB 라인 한눈에 보기',
        image: '/mascot/master_cuts/ch-1_cut3.jpg',
        badge: '코스 구역',
        badgeType: 'info',
        situation: '코스 안과 밖은 어떻게 구분되어 있을까요?',
        parkyDialogue: '코스는 티잉그라운드, 페어웨이, 러프, 벙커, 워터 해저드, 그린의 5개 인플레이 구역과 하얀 말뚝 밖 OB 구역으로 나뉘어요! 구역마다 적용되는 룰이 다르답니다!',
        verdict: '인플레이 5개 구역 + 코스 외곽 OB 구역',
        keyPoint: '공이 어디에 멈추느냐에 따라 적용되는 구제 및 벌타 규정이 결정됩니다.',
        article: '제1장 제2조 제2항',
      },
    ],
  },
  'ch-2': {
    chapterId: 'ch-2',
    chapterNumber: '제2장',
    title: '용구와 복장 수칙',
    subtitle: '협회 공인 인증 스티커와 티 높이 2.3cm의 비밀',
    coverImage: '/mascot/master_cuts/ch-2_cover.jpg',
    totalCuts: 2,
    cuts: [
      {
        cutNumber: 1,
        title: '협회 공인 스티커가 없으면 실격?!',
        image: '/mascot/master_cuts/ch-2_cut1.jpg',
        badge: '실격 주의',
        badgeType: 'penalty',
        situation: '대회 출전 전 클럽과 볼에 어떤 마크가 있어야 할까요?',
        parkyDialogue: '선배님들! 클럽과 볼에 (사)대한파크골프협회 공인 검정 합격 스티커가 붙어있는지 꼭 확인하세요! 미인증 용구는 정규 대회에서 즉시 실격(DQ) 처리된답니다!',
        verdict: '미인증 클럽 및 볼 사용 시 【즉시 실격】',
        penaltyText: '실격 (Disqualified)',
        keyPoint: '클럽 길이 86cm 이하, 중량 600g 이하, 로프트 0도(직각) 공인 클럽만 인정됩니다.',
        article: '제2장 제11조(공인 클럽) & 제12조(공의 규격)',
      },
      {
        cutNumber: 2,
        title: '티 높이는 지면에서 딱 2.3cm 이하!',
        image: '/mascot/master_cuts/ch-2_cut2.jpg',
        badge: '2벌타 주의',
        badgeType: 'caution',
        situation: '개인 고무티를 사용할 때 높이 제한이 있을까요?',
        parkyDialogue: '개인 티를 쓰실 때는 지면으로부터 높이가 2.3cm(23mm)를 넘으면 안 돼요! 너무 높은 롱티로 치면 공인 규정 위반으로 2벌타를 받으니 꼭 규격 티를 사용해 주세요!',
        verdict: '티 높이 2.3cm 이하 고무티만 허용',
        penaltyText: '규정 위반 티 사용 시 2벌타',
        keyPoint: '지정 고무티를 권장하며, 개인 티는 2.3cm 이하 고무 재질만 적법합니다.',
        article: '제2장 제13조 (티의 높이 및 보조용구)',
      },
    ],
  },
  'ch-3': {
    chapterId: 'ch-3',
    chapterNumber: '제3장',
    title: '티샷과 스트로크 일반',
    subtitle: '헛스윙 타수 계산과 매트 스탠스 수칙',
    coverImage: '/mascot/master_cuts/ch-3_cover.jpg',
    totalCuts: 2,
    cuts: [
      {
        cutNumber: 1,
        title: '헛스윙했는데 공을 안 맞췄어요. 타수인가요?',
        image: '/mascot/master_cuts/ch-3_cut1.jpg',
        badge: '1타 가산',
        badgeType: 'caution',
        situation: '공을 치려고 세게 휘둘렀는데 공에 스치지도 않고 바람만 갈랐습니다.',
        parkyDialogue: '공을 치려는 타격 의사를 가지고 다운스윙을 시작했다면, 바람만 가르고 공을 못 맞췄어도 정상 1타로 계산해요! 벌타는 아니지만 1타가 올라가니 다음이 2타째가 됩니다!',
        verdict: '다운스윙 개시 시 공 미접촉도 【1타 가산】',
        penaltyText: '벌타 아님 (스트로크 1타 인정)',
        keyPoint: '단순한 연습스윙이나 어드레스 취소 동작은 타수로 치지 않습니다.',
        article: '제3장 제30조 (스트로크의 정의)',
      },
      {
        cutNumber: 2,
        title: '티샷할 때 두 발이 매트 밖 맨땅으로 나가면?',
        image: '/mascot/master_cuts/ch-3_cut2.jpg',
        badge: '2벌타 주의',
        badgeType: 'penalty',
        situation: '스탠스가 좁다고 매트 밖 맨땅에 두 발을 다 디디고 티샷을 했습니다.',
        parkyDialogue: '발이 편하다고 매트 밖 지면에 두 발을 다 디디고 치면 2벌타예요! 최소한 한 발의 일부(신발 끝이라도)는 티매트 안에 접촉되어 있어야 한답니다!',
        verdict: '양 발 모두 매트 이탈 시 【2벌타】',
        penaltyText: '티잉그라운드 구역 위반 2벌타',
        keyPoint: '두 발 중 적어도 한 발의 일부는 반드시 티매트 안에 닿아 있어야 합니다.',
        article: '제3장 제31조 (티샷 규정 및 스탠스)',
      },
    ],
  },
  'ch-4': {
    chapterId: 'ch-4',
    chapterNumber: '제4장',
    title: 'OB (아웃오브바운즈) 완전정복',
    subtitle: '1mm의 기적과 외곽망 맞고 들어온 공, 2벌타 처치법',
    coverImage: '/mascot/master_cuts/ch-4_cover.jpg',
    totalCuts: 3,
    cuts: [
      {
        cutNumber: 1,
        title: '1mm의 기적! 하얀 선에 살짝 걸친 공은?',
        image: '/mascot/master_cuts/ch-4_cut1.jpg',
        badge: '무벌 세이프',
        badgeType: 'safe',
        situation: '친 공이 굴러가서 하얀 OB 실선에 살짝 닿아 멈췄습니다. OB인가요 세이프인가요?',
        parkyDialogue: '동반자가 OB라고 우겨도 당당하게 말씀하세요! 공 전체가 흰 선 밖으로 완전히 넘어가야만 OB예요! 단 1mm라도 안쪽 선에 닿아 있으면 무조건 무벌 세이프(IN)랍니다!',
        verdict: '공의 일부라도 선에 접촉 시 【세이프(IN)】',
        penaltyText: '벌타 없음 (무벌)',
        keyPoint: '공의 직경 중 단 1mm라도 안쪽 경계선(선 자체 포함)에 걸치면 인플레이 볼입니다.',
        article: '제4장 제33조(OB 및 처치) 제1항',
      },
      {
        cutNumber: 2,
        title: '외곽 그물망이나 나무 맞고 코스 안으로 쏙!',
        image: '/mascot/master_cuts/ch-4_cut2.jpg',
        badge: '기적의 세이프',
        badgeType: 'safe',
        situation: '공이 말뚝 밖으로 날아갔다가 안전망이나 외곽 나무를 맞고 코스 안으로 다시 들어왔습니다.',
        parkyDialogue: '공이 밖으로 날아갔더라도 안전망이나 나무를 맞고 튕겨서 최종적으로 코스 안에 멈췄다면? 파크골프는 최종 정지 위치 기준이므로 무조건 세이프예요! 멈춘 자리에서 그대로 치세요!',
        verdict: '최종 정지 위치가 코스 안이면 【무벌 세이프】',
        penaltyText: '벌타 없음 (무벌 인플레이)',
        keyPoint: '중간 궤적과 상관없이 최종적으로 공이 멈춘 위치가 코스 안이면 세이프입니다.',
        article: '제4장 제33조 제2항 (최종 정지 위치 원칙)',
      },
      {
        cutNumber: 3,
        title: 'OB는 무조건 2벌타! 2클럽 안쪽 처치!',
        image: '/mascot/master_cuts/ch-4_cut3.jpg',
        badge: '2벌타 처치',
        badgeType: 'penalty',
        situation: '공이 완전히 밖으로 나갔습니다. 어디서 몇 타를 받고 쳐야 하나요?',
        parkyDialogue: '파크골프에는 1벌타 OB가 절대 없어요! 무조건 2벌타! 티박스로 돌아가지 않고 공이 나간 지점 코스 안쪽으로 홀에 가깝지 않게 2클럽 이내에 놓고 다음 타를 칩니다!',
        verdict: '【2벌타 가산】 후 OB 통과 지점 2클럽 이내 처치',
        penaltyText: 'OB 발생 시 무조건 2벌타 (1벌타 없음)',
        keyPoint: '티샷이 OB가 난 경우에도 나간 지점 2클럽에서 치는 샷이 제4타가 됩니다.',
        article: '제4장 제33조 제3항',
      },
    ],
  },
  'ch-5': {
    chapterId: 'ch-5',
    chapterNumber: '제5장',
    title: '워터 해저드와 무벌 구제',
    subtitle: '물에 빠진 공 2벌타와 배수구/카트도로 1클럽 무벌 구제',
    coverImage: '/mascot/master_cuts/ch-5_cover.jpg',
    totalCuts: 2,
    cuts: [
      {
        cutNumber: 1,
        title: '워터 해저드(연못/개천)에 풍덩! 어떻게 하나요?',
        image: '/mascot/master_cuts/ch-5_cut1.jpg',
        badge: '2벌타 처치',
        badgeType: 'penalty',
        situation: '공이 워터 해저드 물이나 깊은 수로에 빠져 칠 수 없습니다.',
        parkyDialogue: '물이나 해저드에 빠지면 2벌타가 부과돼요! 공이 해저드 경계를 최종 통과한 지점에서 홀에 가깝지 않게 2클럽 이내 잔디에 놓고 다음 타를 치시면 됩니다!',
        verdict: '워터 해저드 침수 시 【2벌타 가산】',
        penaltyText: '2벌타 후 2클럽 이내 처치',
        keyPoint: '공이 물에 들어간 진입 지점을 기준으로 코스 내 2클럽 헤드 이내에 놓습니다.',
        article: '제5장 제34조 (워터 해저드 및 수리지) 제1항',
      },
      {
        cutNumber: 2,
        title: '배수구 쇠창살, 카트 도로는 1클럽 무벌 구제!',
        image: '/mascot/master_cuts/ch-5_cut2.jpg',
        badge: '무벌 구제',
        badgeType: 'safe',
        situation: '공이 배수구 철망 위나 아스팔트 카트 도로 위에 멈췄습니다.',
        parkyDialogue: '배수구 쇠창살, 아스팔트 카트 도로, 안전망 기둥은 인공 장해물이에요! 아까운 클럽 다치지 않게 홀에 가깝지 않은 잔디 구역으로 1클럽 이내에 무벌로 놓고 치세요!',
        verdict: '움직일 수 없는 인공 장해물 접촉 시 【무벌 1클럽 구제】',
        penaltyText: '벌타 없음 (무벌 구제)',
        keyPoint: '완전 구제 지점으로부터 홀에 가깝지 않은 1클럽 이내 잔디에 공을 놓습니다.',
        article: '제5장 제35조 (장해물) 제1항',
      },
    ],
  },
  'ch-6': {
    chapterId: 'ch-6',
    chapterNumber: '제6장',
    title: '그린과 퍼팅 규정',
    subtitle: '깃대 발거 금지 2벌타와 컵 테두리 걸친 공 판정',
    coverImage: '/mascot/master_cuts/ch-6_cover.jpg',
    totalCuts: 2,
    cuts: [
      {
        cutNumber: 1,
        title: '깃대를 뽑고 퍼팅하면 2벌타?!',
        image: '/mascot/master_cuts/ch-6_cut1.jpg',
        badge: '2벌타 주의',
        badgeType: 'penalty',
        situation: '깃대가 방해된다며 홀컵에서 깃대를 뽑아 바닥에 내려놓고 쳤습니다.',
        parkyDialogue: '일반 골프와 가장 크게 다른 점! 파크골프는 안전과 신속한 경기 진행을 위해 어떤 경우에도 깃대를 뽑을 수 없어요! 깃대를 뽑거나 잡고 치면 2벌타를 받으니 꼭 꽂힌 상태로 치세요!',
        verdict: '깃대 임의 발거 후 퍼팅 시 【2벌타】',
        penaltyText: '깃대 발거 금지 위반 2벌타',
        keyPoint: '파크골프는 깃대를 뽑지 않고 꽂힌 상태로 홀아웃하는 것이 절대 원칙입니다.',
        article: '제6장 제37조 (홀아웃 및 깃대 규정) 제1항',
      },
      {
        cutNumber: 2,
        title: '공이 깃대와 컵 테두리 사이에 끼었어요!',
        image: '/mascot/master_cuts/ch-6_cut2.jpg',
        badge: '홀인 성공',
        badgeType: 'safe',
        situation: '퍼팅한 공이 깃대 봉과 홀 테두리 턱 사이에 끼어 바닥에 떨어지지 않았습니다.',
        parkyDialogue: '당황하지 마시고 동반자가 보는 앞에서 깃대를 조심스럽게 살짝 흔들어보세요! 공이 홀컵 바닥으로 쏙 떨어지면 직전 퍼팅으로 홀아웃 인정이랍니다!',
        verdict: '깃대 흔들어 바닥에 떨어지면 【홀인 인정】',
        penaltyText: '벌타 없음 (홀아웃 성공)',
        keyPoint: '동반자 입회 하에 깃대를 조심스럽게 움직여 바닥에 정지하면 성공입니다.',
        article: '제6장 제37조 제3항 (림 걸침 규정)',
      },
    ],
  },
  'ch-7': {
    chapterId: 'ch-7',
    chapterNumber: '제7장',
    title: '공 충돌과 벌타 총람',
    subtitle: '동반자 공 맞췄을 때 무벌과 남의 공 친 오구 2벌타',
    coverImage: '/mascot/master_cuts/ch-7_cover.jpg',
    totalCuts: 2,
    cuts: [
      {
        cutNumber: 1,
        title: '내 공이 동반자의 정지된 공을 맞췄어요!',
        image: '/mascot/master_cuts/ch-7_cut1.jpg',
        badge: '친 사람 무벌',
        badgeType: 'safe',
        situation: '세컨샷이나 퍼팅을 했는데 앞에 서 있던 동반자의 공을 쾅 맞췄습니다.',
        parkyDialogue: '미안해하지 않으셔도 돼요! 친 분에게는 벌타가 전혀 없고 멈춘 곳에서 그대로 치시면 돼요! 맞아서 움직인 동반자의 공만 원래 있던 자리로 되돌려놓으면 된답니다!',
        verdict: '친 사람 【무벌】 / 맞은 공은 【원위치 리플레이스】',
        penaltyText: '벌타 없음 (무벌)',
        keyPoint: '충돌로 움직인 다른 플레이어의 공만 원래 위치로 리플레이스합니다.',
        article: '제7장 제36조 (공의 충돌 및 오구) 제1항',
      },
      {
        cutNumber: 2,
        title: '남의 공을 내 공인 줄 알고 쳤어요 (오구 플레이)',
        image: '/mascot/master_cuts/ch-7_cut2.jpg',
        badge: '2벌타 주의',
        badgeType: 'penalty',
        situation: '비슷한 색깔의 동반자 공을 내 공인 줄 착각하고 풀스윙으로 쳤습니다.',
        parkyDialogue: '비슷한 공이라도 방심은 금물! 남의 공을 치는 오구 플레이는 2벌타예요! 잘못 친 공은 즉시 제자리로 돌려놓고, 본인의 진짜 공을 찾아 원래 자리에서 치셔야 해요!',
        verdict: '오구 플레이 위반으로 【2벌타 가산】',
        penaltyText: '2벌타 부과',
        keyPoint: '잘못 친 공은 즉시 원위치하고, 2벌타 가산 후 본인 공으로 재개합니다.',
        article: '제7장 제36조 제2항',
      },
    ],
  },
  'ch-8': {
    chapterId: 'ch-8',
    chapterNumber: '제8장',
    title: '스코어 기록과 경기 매너',
    subtitle: '컨시드(OK) 절대 불가와 안전거리 확보',
    coverImage: '/mascot/master_cuts/ch-8_cover.jpg',
    totalCuts: 2,
    cuts: [
      {
        cutNumber: 1,
        title: '파크골프에는 "오케이(컨시드)"가 절대 없어요!',
        image: '/mascot/master_cuts/ch-8_cut1.jpg',
        badge: '실격 주의',
        badgeType: 'penalty',
        situation: '홀컵 10cm 앞에 멈춰서 당연히 들어갈 줄 알고 집은 뒤 다음 홀로 갔습니다.',
        parkyDialogue: '파크골프는 아무리 10cm 짧은 거리라도 "오케이(컨시드)"가 없어요! 컵 바닥에 떨어져 땡그랑 소리를 들을 때까지 쳐야 해요! 안 넣고 다음 홀로 가면 실격 처리된답니다!',
        verdict: '홀아웃 미완료 상태로 다음 홀 티샷 시 【실격】',
        penaltyText: '실격 (Disqualified)',
        keyPoint: '반드시 공이 홀컵 바닥에 멈출 때까지 스트로크를 마쳐야 합니다.',
        article: '제8장 제37조 제4항 & 제45조',
      },
      {
        cutNumber: 2,
        title: '앞 조가 이동하기 전에 치면 절대 안 돼요!',
        image: '/mascot/master_cuts/ch-8_cut2.jpg',
        badge: '안전 에티켓',
        badgeType: 'caution',
        situation: '앞 조가 아직 페어웨이에 서 있는데 뒤에서 그대로 티샷을 날렸습니다.',
        parkyDialogue: '파크골프 공은 매우 단단해서 맞으면 큰 부상으로 이어져요! 앞 조 분들이 완전히 다음 홀 안전지대로 이동한 것을 확인한 뒤에만 티샷해야 해요! 위반 시 2벌타나 퇴장이에요!',
        verdict: '안전거리 미확보 타격 시 【2벌타 또는 실격】',
        penaltyText: '안전 수칙 위반 2벌타',
        keyPoint: '전방 경기자의 안전거리가 완전히 확보된 후에만 스트로크합니다.',
        article: '제8장 제50조 (안전 수칙 및 매너)',
      },
    ],
  },
};

/**
 * 🇯🇵 日本パークゴルフ協会 (NPGA) & 日本語モード専用 公式マンガデータ
 * 韓国語を一切含まない100%自然な日本語公式データ
 */
export const CHAPTER_WEBTOONS_JA: Record<string, ChapterWebtoon> = {
  'npga-ch-1': {
    chapterId: 'npga-ch-1',
    chapterNumber: '第1章',
    title: '総則及びコース・用具規程',
    subtitle: '9ホール33打公認基準と5大コース区域の秘密',
    coverImage: '/mascot/master_cuts/ch-1_cover.jpg',
    totalCuts: 3,
    cuts: [
      {
        cutNumber: 1,
        title: 'パークゴルフの基本！9ホールPar 33の公認規格',
        image: '/mascot/master_cuts/ch-1_cut1.jpg',
        badge: '公認規格',
        badgeType: 'info',
        situation: 'パークゴルフは一般ゴルフとホール数や規定打数がどう違うのでしょうか？',
        parkyDialogue: 'こんにちは！パークゴルフ オールインワン公式マスコットのパーキーです！パークゴルフの公認規格は9ホールでPar 33(合計33打)が標準です！Par 3が4つ、Par 4が4つ、Par 5が1つのバランス良い構成になっています！',
        verdict: '9ホール基準打数 33打 (18ホール 66打)',
        keyPoint: '全コース長は約500m〜700mで、年齢や性別を問わず誰もが安全に楽しめる健康スポーツです。',
        article: '第1章 第2条 (コースの構成及び区域)',
      },
      {
        cutNumber: 2,
        title: 'ティーインググラウンド(マット)区域の秘密',
        image: '/mascot/master_cuts/ch-1_cut2.jpg',
        badge: '出発区域',
        badgeType: 'caution',
        situation: 'ティーショットを打つマット区域はどこまでが正規範囲でしょうか？',
        parkyDialogue: 'ティーインググラウンドは各ホールのスタート地点です！ティーマーカーの前方外面を結ぶ線と、後方2クラブレングス以内の長方形区域から打撃します！両足が完全にマットの外に出ると2打付加(2罰打)になりますのでご注意ください！',
        verdict: 'ティーマーカー前面線 〜 後方2クラブレングスの長方形',
        penaltyText: '両足完全離脱打撃時は2打付加(2罰打)',
        keyPoint: 'ティーショット時は少なくとも片足の一部がティー区域内に接地していなければなりません。',
        article: '第2章 第4条 (ティーインググラウンド区域)',
      },
      {
        cutNumber: 3,
        title: '5大コース区域とOBラインの見分け方',
        image: '/mascot/master_cuts/ch-1_cut3.jpg',
        badge: 'コース区域',
        badgeType: 'info',
        situation: 'コースの内側と外側はどのように区分されているのでしょうか？',
        parkyDialogue: 'コースはティーグラウンド、フェアウェイ、ラフ、バンカー、ウォーターハザード、グリーンの5大インプレー区域と、白杭で示されるOB区域に分かれています！止まった場所によって規則が異なります！',
        verdict: 'インプレー5区域 ＋ コース外周OB区域',
        keyPoint: 'ボールが静止した区域に応じて適用される処置や付加打規則が決定されます。',
        article: '第1章 第2条 第2項',
      },
    ],
  },
  'npga-ch-2': {
    chapterId: 'npga-ch-2',
    chapterNumber: '第2章',
    title: 'ティーインググラウンド及び打撃',
    subtitle: 'NPGA公認マーク必須とティーの高さ23mm制限',
    coverImage: '/mascot/master_cuts/ch-2_cover.jpg',
    totalCuts: 2,
    cuts: [
      {
        cutNumber: 1,
        title: 'NPGA公認マークのない用具は即座に競技失格？！',
        image: '/mascot/master_cuts/ch-2_cut1.jpg',
        badge: '失格注意',
        badgeType: 'penalty',
        situation: '大会出場前にクラブやボールのどのマークを確認すべきでしょうか？',
        parkyDialogue: '皆さん！クラブとボールに日本パークゴルフ協会(NPGA)公認マーク(刻印またはシール)があるか必ず確認してください！未公認用具で出場すると即座に失格(DQ)となります！',
        verdict: '未公認クラブ及びボール使用時は【即座に競技失格】',
        penaltyText: '競技失格 (Disqualified)',
        keyPoint: '重量600g以下、長さ86cm以下、木製ヘッドなどNPGA公認基準に適合した用具のみ有効です。',
        article: '第1章 第3条 (公認クラブ及びボール)',
      },
      {
        cutNumber: 2,
        title: 'ティーの高さは地上から厳格に23mm以下！',
        image: '/mascot/master_cuts/ch-2_cut2.jpg',
        badge: '2打付加',
        badgeType: 'caution',
        situation: 'ティーを使用する際、高さの制限はあるのでしょうか？',
        parkyDialogue: 'ティーショット時は必ずティーを使用し、地上からの高さは23mm以下でなければなりません！高すぎるロングティーを使用すると規則違反で2打付加となります！',
        verdict: 'ティーの高さ23mm以下のみ許容',
        penaltyText: '規定違反ティー使用時 2打付加(2罰打)',
        keyPoint: '常備されている公認ゴムティーの使用が推奨されます。',
        article: '第2章 第5条 (ティーアップとティーの高さ)',
      },
    ],
  },
  'npga-ch-3': {
    chapterId: 'npga-ch-3',
    chapterNumber: '第3章',
    title: 'プレー通則及び障害物の救済',
    subtitle: 'ボールはあるがままの原則と動かせない障害物無罰救済',
    coverImage: '/mascot/master_cuts/ch-5_cover.jpg',
    totalCuts: 2,
    cuts: [
      {
        cutNumber: 1,
        title: 'ボールはあるがまま！ライの改善は禁止！',
        image: '/mascot/master_cuts/ch-5_cut1.jpg',
        badge: '2打付加',
        badgeType: 'penalty',
        situation: '打ちにくいライにある草を足で踏み固めたり枝を折ってスイングしました。',
        parkyDialogue: 'ボールのライやスイング区域の草木を折ったり踏み固めて打ちやすくする行為は厳禁です！あるがままの状態で打たなければならず、違反すると2打付加となります！',
        verdict: 'ライ改善違反時は【2打付加 (2罰打)】',
        penaltyText: 'ライ改善違反 2打付加',
        keyPoint: 'どうしても打てない場合はアンプレヤブルを宣言して2打付加で処置します。',
        article: '第3章 第8条 (球はあるがままの状態) & 第11条',
      },
      {
        cutNumber: 2,
        title: '排水溝・カート道・散水栓は無罰1クラブ救済！',
        image: '/mascot/master_cuts/ch-5_cut2.jpg',
        badge: '無罰救済',
        badgeType: 'safe',
        situation: '排水溝のグレーチングの上や舗装された作業通路にボールが止まりました。',
        parkyDialogue: '排水溝の鉄格子やカート道路、水道栓は「動かせない障害物」です！クラブを傷めないよう、ピンに近づかない最も近い救済点から1クラブレングス以内に無罰でプレース(手で置く)できます！',
        verdict: '動かせない人工障害物接触時は【無罰 1クラブレングス救済】',
        penaltyText: '罰なし (無罰プレース)',
        keyPoint: 'ホールに近づかない救済ポイントから1クラブ以内に手で静かにプレースします。',
        article: '第3章 第9条 (動かない障害物及びカジュアルウォーター)',
      },
    ],
  },
  'npga-ch-4': {
    chapterId: 'npga-ch-4',
    chapterNumber: '第4章',
    title: 'アウトオブバウンズ (OB) 及び境界',
    subtitle: '1mmの奇跡インプレー判定と2打付加手によるプレース',
    coverImage: '/mascot/master_cuts/ch-4_cover.jpg',
    totalCuts: 2,
    cuts: [
      {
        cutNumber: 1,
        title: '1mmの奇跡！白線に少しでも触れていればセーフ！',
        image: '/mascot/master_cuts/ch-4_cut1.jpg',
        badge: '無罰セーフ',
        badgeType: 'safe',
        situation: '打ったボールが転がり、白いOB境界線に少しだけ触れて止まりました。OBでしょうか？',
        parkyDialogue: '自信を持って同伴者に伝えてください！ボール全体が白線の外側に完全に静止したときだけがOBです！真上から見て1mmでも白線に触れていれば無罰でセーフ(インプレー)です！',
        verdict: 'ボールの一部が白線に接触していれば【セーフ (インプレー)】',
        penaltyText: '罰打なし (無罰)',
        keyPoint: 'ボールの直径のうちわずか1mmでも白線上に触れていれば生きています。',
        article: '第4章 第12条 (OBの定義及び判定)',
      },
      {
        cutNumber: 2,
        title: 'OBは必ず2打付加！境界通過地点から2クラブ手でプレース！',
        image: '/mascot/master_cuts/ch-4_cut3.jpg',
        badge: '2打付加',
        badgeType: 'penalty',
        situation: 'ボールが白線を完全に越えてOBになりました。どこから何打で打つべきでしょうか？',
        parkyDialogue: 'パークゴルフのOBは必ず2打付加(2罰打)です！ティーグラウンドには戻らず、ボールがOB線を最後に横切った地点から、ホールに近づかないコース内に2クラブレングス以内で手で静かに置いて次を打ちます！',
        verdict: '【2打付加】の後、境界通過地点から2クラブ以内に手でプレース',
        penaltyText: 'OB発生時は必ず2打付加 (1打付加のOBはありません)',
        keyPoint: 'ティーショットがOBの場合も、境界横切地点からのショットが第4打目となります。',
        article: '第4章 第13条 (OBの救済処置)',
      },
    ],
  },
  'npga-ch-5': {
    chapterId: 'npga-ch-5',
    chapterNumber: '第5章',
    title: 'パッティンググリーン及びホールアウト',
    subtitle: 'グリーン上のマーク義務とコンシード(OK)絶対不可',
    coverImage: '/mascot/master_cuts/ch-6_cover.jpg',
    totalCuts: 2,
    cuts: [
      {
        cutNumber: 1,
        title: 'グリーン上でのボールマークとピックアップ義務',
        image: '/mascot/master_cuts/ch-6_cut1.jpg',
        badge: 'マーク義務',
        badgeType: 'info',
        situation: 'グリーン上で自分のボールが同伴者のパッティングラインの邪魔になっています。',
        parkyDialogue: '同伴者から要請があった場合はもちろん、カップから2クラブ以内にあるボールは自発的にボールマーカーをボールの真後ろに置いて拾い上げましょう！安全でスムーズな進行のマナーです！',
        verdict: '要請時は必ずボール直後にマークを設置してピックアップ',
        penaltyText: 'マーク怠慢で他者の打球が当たっても打者は無罰(当たった球は復元)',
        keyPoint: 'マーカーはボールの直後(真後ろ)に密着して設置し、打撃後に正確に元の位置に戻します。',
        article: '第5章 第14条 (マークとピックアップ)',
      },
      {
        cutNumber: 2,
        title: 'コンシード(OK)は絶対不可！底に落ちるまでホールアウト！',
        image: '/mascot/master_cuts/ch-8_cut1.jpg',
        badge: '失格注意',
        badgeType: 'penalty',
        situation: 'カップのすぐ縁に止まり、OKと思って拾い上げて次のホールへ向かいました。',
        parkyDialogue: 'パークゴルフには「OK(コンシード)」は一切ありません！どれほど近くてもカップの底にカランと落ちて静止するまで打ち終えなければなりません！拾ったまま次のホールを打つと競技失格(DQ)になります！',
        verdict: 'ホールアウト未完了のまま次ホールを打撃した場合は【競技失格】',
        penaltyText: '競技失格 (Disqualified)',
        keyPoint: '必ずボールがカップの底に静止するまでストロークを完了させます。',
        article: '第5章 第15条 (カップインの判定) & 第16条',
      },
    ],
  },
  // Korean Chapter IDs mapped to Japanese as fallback
  'ch-1': {
    chapterId: 'ch-1',
    chapterNumber: '第1章',
    title: 'コース探検と基本規程',
    subtitle: '9ホール33打公認基準と5大コース区域の秘密',
    coverImage: '/mascot/master_cuts/ch-1_cover.jpg',
    totalCuts: 3,
    cuts: [
      {
        cutNumber: 1,
        title: 'パークゴルフの基本！9ホールPar 33の公認規格',
        image: '/mascot/master_cuts/ch-1_cut1.jpg',
        badge: '公認規格',
        badgeType: 'info',
        situation: 'パークゴルフは一般ゴルフとホール数や規定打数がどう違うのでしょうか？',
        parkyDialogue: 'こんにちは！パークゴルフ オールインワン公式マスコットのパーキーです！パークゴルフの公認規格は9ホールでPar 33(合計33打)が標準です！Par 3が4つ、Par 4が4つ、Par 5が1つのバランス良い構成になっています！',
        verdict: '9ホール基準打数 33打 (18ホール 66打)',
        keyPoint: '全コース長は約500m〜700mで、年齢や性別を問わず誰もが安全に楽しめる健康スポーツです。',
        article: '第1章 第2条 (コースの構成及び区域)',
      },
      {
        cutNumber: 2,
        title: 'ティーインググラウンド(マット)区域の秘密',
        image: '/mascot/master_cuts/ch-1_cut2.jpg',
        badge: '出発区域',
        badgeType: 'caution',
        situation: 'ティーショットを打つマット区域はどこまでが正規範囲でしょうか？',
        parkyDialogue: 'ティーインググラウンドは各ホールのスタート地点です！ティーマーカーの前方外面を結ぶ線と、後方2クラブレングス以内の長方形区域から打撃します！両足が完全にマットの外に出ると2打付加(2罰打)になりますのでご注意ください！',
        verdict: 'ティーマーカー前面線 〜 後方2クラブレングスの長方形',
        penaltyText: '両足完全離脱打撃時は2打付加(2罰打)',
        keyPoint: 'ティーショット時は少なくとも片足の一部がティー区域内に接地していなければなりません。',
        article: '第2章 第4条 (ティーインググラウンド区域)',
      },
      {
        cutNumber: 3,
        title: '5大コース区域とOBラインの見分け方',
        image: '/mascot/master_cuts/ch-1_cut3.jpg',
        badge: 'コース区域',
        badgeType: 'info',
        situation: 'コースの内側と外側はどのように区分されているのでしょうか？',
        parkyDialogue: 'コースはティーグラウンド、フェアウェイ、ラフ、バンカー、ウォーターハザード、グリーンの5大インプレー区域と、白杭で示されるOB区域に分かれています！止まった場所によって規則が異なります！',
        verdict: 'インプレー5区域 ＋ コース外周OB区域',
        keyPoint: 'ボールが静止した区域に応じて適用される処置や付加打規則が決定されます。',
        article: '第1章 第2条 第2項',
      },
    ],
  },
  'ch-2': {
    chapterId: 'ch-2',
    chapterNumber: '第2章',
    title: '用具と服装のマナー',
    subtitle: '協会公認認証マークとティーの高さ23mmの秘密',
    coverImage: '/mascot/master_cuts/ch-2_cover.jpg',
    totalCuts: 2,
    cuts: [
      {
        cutNumber: 1,
        title: '公認マークのない用具は即座に失格？！',
        image: '/mascot/master_cuts/ch-2_cut1.jpg',
        badge: '失格注意',
        badgeType: 'penalty',
        situation: '大会出場前にクラブとボールのどのマークを確認すべきでしょうか？',
        parkyDialogue: '皆さん！クラブとボールに協会公認マークが貼られているか必ず確認してください！未公認用具は正規大会で即座に失格(DQ)となります！',
        verdict: '未公認用具使用時は【即座に競技失格】',
        penaltyText: '競技失格 (Disqualified)',
        keyPoint: 'クラブ長さ86cm以下、重量600g以下、ロフト角0度(直角)の公認クラブのみ認められます。',
        article: '第2章 第11条(公認クラブ) & 第12条(ボール規格)',
      },
      {
        cutNumber: 2,
        title: 'ティーの高さは地上から厳格に23mm以下！',
        image: '/mascot/master_cuts/ch-2_cut2.jpg',
        badge: '2打付加',
        badgeType: 'caution',
        situation: '個人ティーを使用する際、高さ制限はあるのでしょうか？',
        parkyDialogue: '個人ティーを使用する場合、地上からの高さが23mm(2.3cm)を超えてはいけません！高すぎるロングティーを使用すると規則違反で2打付加となります！',
        verdict: 'ティーの高さ23mm以下のゴムティーのみ許容',
        penaltyText: '規定違反ティー使用時 2打付加',
        keyPoint: '常備されている公認ゴムティーの使用を推奨します。',
        article: '第2章 第13条 (ティーの高さ及び補助用具)',
      },
    ],
  },
  'ch-3': {
    chapterId: 'ch-3',
    chapterNumber: '第3章',
    title: 'ティーショットとストローク通則',
    subtitle: '空振りの打数計算とマットスタンス規則',
    coverImage: '/mascot/master_cuts/ch-3_cover.jpg',
    totalCuts: 2,
    cuts: [
      {
        cutNumber: 1,
        title: '空振りでボールに当たらなかった場合は打数になる？',
        image: '/mascot/master_cuts/ch-3_cut1.jpg',
        badge: '1打加算',
        badgeType: 'caution',
        situation: '打つ意思を持って強く振りましたが、ボールに当たらず空を切りました。',
        parkyDialogue: 'ボールを打つ意思を持ってダウンスイングを開始した場合、空振りであっても正規の1打としてカウントされます！罰打ではありませんが1打加算され次は第2打となります！',
        verdict: 'ダウンスイング開始時は空振りでも【1打加算】',
        penaltyText: '罰打なし (ストローク1打認定)',
        keyPoint: '単なる練習スイングやアドレス中断の動作は打数に数えません。',
        article: '第3章 第30条 (ストロークの定義)',
      },
      {
        cutNumber: 2,
        title: 'ティーショットで両足がマットの外の地面に出たら？',
        image: '/mascot/master_cuts/ch-3_cut2.jpg',
        badge: '2打付加',
        badgeType: 'penalty',
        situation: 'スタンスが狭いと感じ、マットの外の地面に両足を置いて打ちました。',
        parkyDialogue: '打ちやすいからとマットの外の地面に両足を完全に置いて打つと2打付加です！少なくとも片足の一部はティーマット内に接触していなければなりません！',
        verdict: '両足完全離脱時は【2打付加】',
        penaltyText: 'ティー区域違反 2打付加',
        keyPoint: '両足のうち少なくとも一方の足の一部は必ずティーマット内に接触している必要があります。',
        article: '第3章 第31条 (ティーショット規程及びスタンス)',
      },
    ],
  },
  'ch-4': {
    chapterId: 'ch-4',
    chapterNumber: '第4章',
    title: 'アウトオブバウンズ (OB) 完全攻略',
    subtitle: '1mmの奇跡と外周フェンス接触球、2打付加処置',
    coverImage: '/mascot/master_cuts/ch-4_cover.jpg',
    totalCuts: 3,
    cuts: [
      {
        cutNumber: 1,
        title: '1mmの奇跡！白い境界線に触れているボールは？',
        image: '/mascot/master_cuts/ch-4_cut1.jpg',
        badge: '無罰セーフ',
        badgeType: 'safe',
        situation: '打ったボールが白線にわずかに触れて止まりました。OBでしょうか？',
        parkyDialogue: '同伴者に自信を持って伝えてください！ボール全体が白線の外側に完全に静止したときだけがOBです！真上から見て1mmでも白線に触れていれば無罰でセーフです！',
        verdict: 'ボールの一部が白線に接触していれば【セーフ (インプレー)】',
        penaltyText: '罰打なし (無罰)',
        keyPoint: 'ボールの直径のうちわずか1mmでも境界線上に触れていればインプレー球です。',
        article: '第4章 第33条(OB及び処置) 第1項',
      },
      {
        cutNumber: 2,
        title: '外周防球ネットや木に当たってコース内へ戻った！',
        image: '/mascot/master_cuts/ch-4_cut2.jpg',
        badge: '奇跡のセーフ',
        badgeType: 'safe',
        situation: '白杭の外へ飛んだボールが安全ネットや立木に跳ね返ってコース内に止まりました。',
        parkyDialogue: '一度外へ飛んだボールでも、ネットや立木に当たって最終的にコース内に静止した場合は無罰でセーフです！止まった場所からそのまま打ってください！',
        verdict: '最終静止位置がコース内であれば【無罰セーフ】',
        penaltyText: '罰打なし (無罰インプレー)',
        keyPoint: '飛行中の軌跡にかかわらず、ボールが静止した最終位置がコース内であれば有効です。',
        article: '第4章 第33条 第2項 (最終静止位置の原則)',
      },
      {
        cutNumber: 3,
        title: 'OBは必ず2打付加！境界通過地点から2クラブ以内処置！',
        image: '/mascot/master_cuts/ch-4_cut3.jpg',
        badge: '2打付加',
        badgeType: 'penalty',
        situation: 'ボールが白線を完全に越えました。どこから何打で打つべきでしょうか？',
        parkyDialogue: 'パークゴルフのOBは必ず2打付加です！ティーボックスには戻らず、ボールがOB境界を横切った地点からホールに近づかないコース内に2クラブレングス以内で手で置いて打ちます！',
        verdict: '【2打付加】後、境界通過地点から2クラブ以内にプレース',
        penaltyText: 'OB発生時は必ず2打付加 (1打付加のOBはありません)',
        keyPoint: 'ティーショットがOBの場合も、境界横切地点からの次打が第4打となります。',
        article: '第4章 第33条 第3項',
      },
    ],
  },
  'ch-5': {
    chapterId: 'ch-5',
    chapterNumber: '第5章',
    title: 'ウォーターハザードと無罰救済',
    subtitle: '水没ボール2打付加と排水溝・カート道1クラブ無罰救済',
    coverImage: '/mascot/master_cuts/ch-5_cover.jpg',
    totalCuts: 2,
    cuts: [
      {
        cutNumber: 1,
        title: '池や水路にポチャリ！どう処置する？',
        image: '/mascot/master_cuts/ch-5_cut1.jpg',
        badge: '2打付加',
        badgeType: 'penalty',
        situation: 'ボールが池や深い水路に入り打つことができません。',
        parkyDialogue: 'ウォーターハザードに入った場合は2打付加となります！ボールがハザード境界を最後に横切った地点から、ホールに近づかない2クラブレングス以内に置いて次打を打ちます！',
        verdict: '水没時は【2打付加加算】',
        penaltyText: '2打付加後 2クラブ以内処置',
        keyPoint: '入水地点を基準に、ホールに近づかないコース内に2クラブレングス以内で静かにプレースします。',
        article: '第5章 第34条 (ウォーターハザード及び修理地) 第1項',
      },
      {
        cutNumber: 2,
        title: '排水溝のグレーチングやカート道は無罰1クラブ救済！',
        image: '/mascot/master_cuts/ch-5_cut2.jpg',
        badge: '無罰救済',
        badgeType: 'safe',
        situation: 'ボールが排水溝の鉄格子の上やアスファルト作業通路で止まりました。',
        parkyDialogue: '排水溝の鉄格子やカート道は「動かせない人工障害物」です！クラブを痛めないよう、ピンに近づかない芝生区域へ1クラブレングス以内に無罰で置いて打ってください！',
        verdict: '動かせない人工障害物接触時は【無罰 1クラブレングス救済】',
        penaltyText: '罰打なし (無罰救済)',
        keyPoint: '完全な救済地点からピンに近づかない1クラブレングス以内の芝生にボールを置きます。',
        article: '第5章 第35条 (障害物) 第1項',
      },
    ],
  },
  'ch-6': {
    chapterId: 'ch-6',
    chapterNumber: '第6章',
    title: 'グリーンとパッティング規定',
    subtitle: 'ピン抜きの禁止とカップ縁のボール判定',
    coverImage: '/mascot/master_cuts/ch-6_cover.jpg',
    totalCuts: 2,
    cuts: [
      {
        cutNumber: 1,
        title: 'ピンを抜いてパッティングすると2打付加？！',
        image: '/mascot/master_cuts/ch-6_cut1.jpg',
        badge: '2打付加',
        badgeType: 'penalty',
        situation: 'ピンが邪魔だとカップから引き抜いて地面に置いて打ちました。',
        parkyDialogue: '一般ゴルフと最も大きく異なるポイント！パークゴルフでは安全と迅速な進行のためピンを抜くことが固く禁止されています！抜いて打つと2打付加になりますので必ず立てたまま打ってください！',
        verdict: 'ピン任意抜去後のパッティングは【2打付加】',
        penaltyText: 'ピン抜去禁止違反 2打付加',
        keyPoint: 'パークゴルフはピンを立てたままホールアウトすることが絶対の原則です。',
        article: '第6章 第37条 (ホールアウト及びピン規定) 第1項',
      },
      {
        cutNumber: 2,
        title: 'ボールがピンとカップ縁の間に挟まった！',
        image: '/mascot/master_cuts/ch-6_cut2.jpg',
        badge: 'カップイン',
        badgeType: 'safe',
        situation: 'パッティングしたボールがピンのポールとカップの縁の間に挟まり底に落ちていません。',
        parkyDialogue: '慌てず同伴者の立ち会いのもとでピンをゆっくり軽く揺らしてみてください！ボールがカップの底にカランと落ちれば直前のストロークでカップイン認定です！',
        verdict: 'ピンを揺らして底に落ちれば【カップイン認定】',
        penaltyText: '罰打なし (ホールアウト成功)',
        keyPoint: '同伴者立ち会いのもと慎重に動かし、底に静止すればホールアウト成功です。',
        article: '第6章 第37条 第3項',
      },
    ],
  },
  'ch-7': {
    chapterId: 'ch-7',
    chapterNumber: '第7章',
    title: 'ボールの衝突と付加打総覧',
    subtitle: '同伴者のボールに当たった時の無罰と誤球2打付加',
    coverImage: '/mascot/master_cuts/ch-7_cover.jpg',
    totalCuts: 2,
    cuts: [
      {
        cutNumber: 1,
        title: '打ったボールが同伴者の静止球に当たった！',
        image: '/mascot/master_cuts/ch-7_cut1.jpg',
        badge: '打者無罰',
        badgeType: 'safe',
        situation: 'セカンドショットやパッティングで前方に静止していた同伴者のボールに直撃しました。',
        parkyDialogue: '慌てなくて大丈夫です！打った方には一切ペナルティはなく止まった場所からそのまま次を打ちます！当たって動いた同伴者のボールだけを元あった場所に戻せばOKです！',
        verdict: '打った人は【無罰】 / 当てられた球は【元位置へリプレース】',
        penaltyText: '罰打なし (無罰)',
        keyPoint: '衝突で動いた他の競技者のボールのみ元の位置へリプレースします。',
        article: '第7章 第36条 (球の衝突及び誤球) 第1項',
      },
      {
        cutNumber: 2,
        title: '他人のボールを自分の球と勘違いして打った (誤球)',
        image: '/mascot/master_cuts/ch-7_cut2.jpg',
        badge: '2打付加',
        badgeType: 'penalty',
        situation: 'よく似た色の同伴者のボールを自分の球だと思い込みフルスイングしました。',
        parkyDialogue: '似た色のボールでも油断禁物！他人の球を打つ「誤球プレー」は2打付加です！間違えて打った球は直ちに元の位置へ戻し、自分の球を探して元位置から打ち直してください！',
        verdict: '誤球プレー違反により【2打付加】',
        penaltyText: '誤球 2打付加',
        keyPoint: '間違えた球は速やかに元位置へ戻し、2打付加加算の上で自球で再開します。',
        article: '第7章 第36条 第2項',
      },
    ],
  },
  'ch-8': {
    chapterId: 'ch-8',
    chapterNumber: '第8章',
    title: 'スコア記録と競技マナー',
    subtitle: 'コンシード(OK)絶対不可と安全距離確保',
    coverImage: '/mascot/master_cuts/ch-8_cover.jpg',
    totalCuts: 2,
    cuts: [
      {
        cutNumber: 1,
        title: 'パークゴルフに「OK(コンシード)」は絶対ありません！',
        image: '/mascot/master_cuts/ch-8_cut1.jpg',
        badge: '失格注意',
        badgeType: 'penalty',
        situation: 'カップ10cm前に止まり、入ると思って拾い上げて次ホールへ向かいました。',
        parkyDialogue: 'パークゴルフはどんなに短い距離でも「OK(コンシード)」はありません！カップの底にカランと落ちるまで打ち終えなければならず、入れずに次ホールを打つと競技失格(DQ)となります！',
        verdict: 'ホールアウト未完了で次ホールを打った場合は【競技失格】',
        penaltyText: '競技失格 (Disqualified)',
        keyPoint: '必ずボールがカップの底に落ちて静止するまでストロークを完了させます。',
        article: '第8章 第37条 第4項 & 第45条',
      },
      {
        cutNumber: 2,
        title: '前の組が移動する前に打つのは絶対禁止！',
        image: '/mascot/master_cuts/ch-8_cut2.jpg',
        badge: '安全マナー',
        badgeType: 'caution',
        situation: '前の組がまだフェアウェイにいる状態でそのままティーショットを打ちました。',
        parkyDialogue: 'パークゴルフのボールはとても硬く、当たると大怪我につながります！前の組の皆様が完全に次のホールの安全地帯へ移動したことを確認してから打ってください！違反時は2打付加や退場処分となります！',
        verdict: '安全距離未確保での打撃は【2打付加または失格】',
        penaltyText: '安全マナー違反 2打付加',
        keyPoint: '前方競技者の安全距離が完全に確保された後にのみストロークを行います。',
        article: '第8章 第50条 (安全規則及びマナー)',
      },
    ],
  },
};

/**
 * 🌐 챕터별 웹툰 다국어 반환 함수 (한국어 / 일본어 1:1 완벽 대응)
 */
export function getChapterWebtoon(chapterId: string, isJapanese: boolean): ChapterWebtoon | undefined {
  if (isJapanese) {
    if (CHAPTER_WEBTOONS_JA[chapterId]) {
      return CHAPTER_WEBTOONS_JA[chapterId];
    }
    // 'ch-1' 형태 등 fallback 대응
    const normalizedId = chapterId.startsWith('npga-') ? chapterId : `npga-${chapterId}`;
    if (CHAPTER_WEBTOONS_JA[normalizedId]) {
      return CHAPTER_WEBTOONS_JA[normalizedId];
    }
  }

  // Korean default
  const base = CHAPTER_WEBTOONS[chapterId];
  if (base) return base;

  // If requested with 'npga-ch-1' in Korean mode, strip prefix
  const strippedId = chapterId.replace('npga-', '');
  return CHAPTER_WEBTOONS[strippedId];
}
