export interface ChapterWebtoonCut {
  cutNumber: number;
  title: string;
  image: string;
  badge: string;
  badgeType: 'safe' | 'penalty' | 'caution' | 'info';
  situation: string;
  parkyDialogue: string;
  verdict: string;
  penaltyText?: string;
  keyPoint: string;
  article: string;
}

export interface ChapterWebtoon {
  chapterId: string;
  chapterNumber: string;
  title: string;
  subtitle: string;
  coverImage: string;
  totalCuts: number;
  cuts: ChapterWebtoonCut[];
}

export const CHAPTER_WEBTOONS: Record<string, ChapterWebtoon> = {
  'ch-1': {
    chapterId: 'ch-1',
    chapterNumber: '제1장',
    title: '코스 탐험과 기본 규정',
    subtitle: '9홀 33타 공인 기준과 5대 코스 구역의 비밀',
    coverImage: '/mascot/사진저장고_사진_20260913_28.jpg',
    totalCuts: 3,
    cuts: [
      {
        cutNumber: 1,
        title: '파크골프의 정석! 9홀 Par 33 공인 규격',
        image: '/mascot/사진저장고_사진_20260913_28.jpg',
        badge: '공인 규격',
        badgeType: 'info',
        situation: '파크골프는 일반 골프와 홀수 및 기준 타수가 어떻게 다를까요?',
        parkyDialogue: '안녕하세요! 파크온 마스코트 파키예요! 파크골프 공인 규격은 9홀 기준 총 33타(Par 33)가 표준이랍니다! Par 3 4개, Par 4 4개, Par 5 1개로 알차게 구성되어 있어요!',
        verdict: '9홀 기준 기준타수 33타 (18홀 66타)',
        keyPoint: '전체 거리는 9홀 약 660m 내외로 남녀노소 누구나 걷기 좋은 도심 속 친환경 코스입니다.',
        article: '제1장 제2조 (코스의 구성 및 구역)',
      },
      {
        cutNumber: 2,
        title: '티잉그라운드(티박스) 매트 구역의 비밀',
        image: '/mascot/사진저장고_사진_20260913_30.jpg',
        badge: '출발 구역',
        badgeType: 'caution',
        situation: '티샷을 날리는 매트는 어디까지가 정규 구역일까요?',
        parkyDialogue: '티박스는 각 홀의 출발점이에요! 인조잔디 매트 또는 양측 티마커 전면선 뒤쪽 2클럽 이내 직사각형 구역에서만 티샷이 가능해요! 두 발이 모두 나가면 2벌타를 받으니 꼭 주의하세요!',
        verdict: '티마커 전면선 ~ 후방 2클럽 직사각형',
        penaltyText: '두 발 모두 매트 이탈 시 2벌타',
        keyPoint: '티샷 시 최소 한 발의 일부는 반드시 매트 안에 닿아 있어야 합니다.',
        article: '제1장 제3조 (티잉그라운드) & 제31조',
      },
      {
        cutNumber: 3,
        title: '5대 코스 구역과 OB 라인 한눈에 보기',
        image: '/mascot/사진저장고_사진_20260913_34.jpg',
        badge: '코스 구역',
        badgeType: 'info',
        situation: '코스 안과 밖은 어떻게 구분되어 있을까요?',
        parkyDialogue: '코스는 티잉그라운드, 페어웨이, 러프, 벙커, 워터 해저드, 그린의 5개 인플레이 구역과 하얀 말뚝 밖 OB 구역으로 나뉘어요! 구역마다 적용되는 룰이 다르답니다!',
        verdict: '인플레이 5개 구역 + 코스 외곽 OB 구역',
        keyPoint: '공이 어디에 멈추느냐에 따라 적용되는 구제 및 벌타 규정이 결정됩니다.',
        article: '제1장 제2조 제2항',
      },
    ],
  },
  'ch-2': {
    chapterId: 'ch-2',
    chapterNumber: '제2장',
    title: '용구와 복장 수칙',
    subtitle: '협회 공인 인증 스티커와 티 높이 2.3cm의 비밀',
    coverImage: '/mascot/사진저장고_사진_20260913_31.jpg',
    totalCuts: 2,
    cuts: [
      {
        cutNumber: 1,
        title: '협회 공인 스티커가 없으면 실격?!',
        image: '/mascot/사진저장고_사진_20260913_31.jpg',
        badge: '실격 주의',
        badgeType: 'penalty',
        situation: '대회 출전 전 클럽과 볼에 어떤 마크가 있어야 할까요?',
        parkyDialogue: '선배님들! 클럽과 볼에 (사)대한파크골프협회 공인 검정 합격 스티커가 붙어있는지 꼭 확인하세요! 미인증 용구는 정규 대회에서 즉시 실격(DQ) 처리된답니다!',
        verdict: '미인증 클럽 및 볼 사용 시 【즉시 실격】',
        penaltyText: '실격 (Disqualified)',
        keyPoint: '클럽 길이 86cm 이하, 중량 600g 이하, 로프트 0도(직각) 공인 클럽만 인정됩니다.',
        article: '제2장 제11조(공인 클럽) & 제12조(공의 규격)',
      },
      {
        cutNumber: 2,
        title: '티 높이는 지면에서 딱 2.3cm 이하!',
        image: '/mascot/사진저장고_사진_20260913_37.jpg',
        badge: '2벌타 주의',
        badgeType: 'caution',
        situation: '개인 고무티를 사용할 때 높이 제한이 있을까요?',
        parkyDialogue: '개인 티를 쓰실 때는 지면으로부터 높이가 2.3cm(23mm)를 넘으면 안 돼요! 너무 높은 롱티로 치면 공인 규정 위반으로 2벌타를 받으니 꼭 규격 티를 사용해 주세요!',
        verdict: '티 높이 2.3cm 이하 고무티만 허용',
        penaltyText: '규정 위반 티 사용 시 2벌타',
        keyPoint: '지정 고무티를 권장하며, 개인 티는 2.3cm 이하 고무 재질만 적법합니다.',
        article: '제2장 제13조 (티의 높이 및 보조용구)',
      },
    ],
  },
  'ch-3': {
    chapterId: 'ch-3',
    chapterNumber: '제3장',
    title: '티샷과 스트로크 일반',
    subtitle: '헛스윙 타수 계산과 매트 스탠스 수칙',
    coverImage: '/mascot/사진저장고_사진_20260913_30.jpg',
    totalCuts: 2,
    cuts: [
      {
        cutNumber: 1,
        title: '헛스윙했는데 공을 안 맞췄어요. 타수인가요?',
        image: '/mascot/사진저장고_사진_20260913_30.jpg',
        badge: '1타 가산',
        badgeType: 'caution',
        situation: '공을 치려고 세게 휘둘렀는데 공에 스치지도 않고 바람만 갈랐습니다.',
        parkyDialogue: '공을 치려는 타격 의사를 가지고 다운스윙을 시작했다면, 바람만 가르고 공을 못 맞췄어도 정상 1타로 계산해요! 벌타는 아니지만 1타가 올라가니 다음이 2타째가 됩니다!',
        verdict: '다운스윙 개시 시 공 미접촉도 【1타 가산】',
        penaltyText: '벌타 아님 (스트로크 1타 인정)',
        keyPoint: '단순한 연습스윙이나 어드레스 취소 동작은 타수로 치지 않습니다.',
        article: '제3장 제30조 (스트로크의 정의)',
      },
      {
        cutNumber: 2,
        title: '티샷할 때 두 발이 매트 밖 맨땅으로 나가면?',
        image: '/mascot/사진저장고_사진_20260913_40.jpg',
        badge: '2벌타 주의',
        badgeType: 'penalty',
        situation: '스탠스가 좁다고 매트 밖 맨땅에 두 발을 다 디디고 티샷을 했습니다.',
        parkyDialogue: '발이 편하다고 매트 밖 지면에 두 발을 다 디디고 치면 2벌타예요! 최소한 한 발의 일부(신발 끝이라도)는 티매트 안에 접촉되어 있어야 한답니다!',
        verdict: '양 발 모두 매트 이탈 시 【2벌타】',
        penaltyText: '티잉그라운드 구역 위반 2벌타',
        keyPoint: '두 발 중 적어도 한 발의 일부는 반드시 티매트 안에 닿아 있어야 합니다.',
        article: '제3장 제31조 (티샷 규정 및 스탠스)',
      },
    ],
  },
  'ch-4': {
    chapterId: 'ch-4',
    chapterNumber: '제4장',
    title: 'OB (아웃오브바운즈) 완전정복',
    subtitle: '1mm의 기적과 외곽망 맞고 들어온 공, 2벌타 처치법',
    coverImage: '/mascot/사진저장고_사진_20260913_41.jpg',
    totalCuts: 3,
    cuts: [
      {
        cutNumber: 1,
        title: '1mm의 기적! 하얀 선에 살짝 걸친 공은?',
        image: '/mascot/사진저장고_사진_20260913_41.jpg',
        badge: '무벌 세이프',
        badgeType: 'safe',
        situation: '친 공이 굴러가서 하얀 OB 실선에 살짝 닿아 멈췄습니다. OB인가요 세이프인가요?',
        parkyDialogue: '동반자가 OB라고 우겨도 당당하게 말씀하세요! 공 전체가 흰 선 밖으로 완전히 넘어가야만 OB예요! 단 1mm라도 안쪽 선에 닿아 있으면 무조건 무벌 세이프(IN)랍니다!',
        verdict: '공의 일부라도 선에 접촉 시 【세이프(IN)】',
        penaltyText: '벌타 없음 (무벌)',
        keyPoint: '공의 직경 중 단 1mm라도 안쪽 경계선(선 자체 포함)에 걸치면 인플레이 볼입니다.',
        article: '제4장 제33조(OB 및 처치) 제1항',
      },
      {
        cutNumber: 2,
        title: '외곽 그물망이나 나무 맞고 코스 안으로 쏙!',
        image: '/mascot/사진저장고_사진_20260913_1.jpg',
        badge: '기적의 세이프',
        badgeType: 'safe',
        situation: '공이 말뚝 밖으로 날아갔다가 안전망이나 외곽 나무를 맞고 코스 안으로 다시 들어왔습니다.',
        parkyDialogue: '공이 밖으로 날아갔더라도 안전망이나 나무를 맞고 튕겨서 최종적으로 코스 안에 멈췄다면? 파크골프는 최종 정지 위치 기준이므로 무조건 세이프예요! 멈춘 자리에서 그대로 치세요!',
        verdict: '최종 정지 위치가 코스 안이면 【무벌 세이프】',
        penaltyText: '벌타 없음 (무벌 인플레이)',
        keyPoint: '중간 궤적과 상관없이 최종적으로 공이 멈춘 위치가 코스 안이면 세이프입니다.',
        article: '제4장 제33조 제2항 (최종 정지 위치 원칙)',
      },
      {
        cutNumber: 3,
        title: 'OB는 무조건 2벌타! 2클럽 안쪽 처치!',
        image: '/mascot/사진저장고_사진_20260913_34.jpg',
        badge: '2벌타 처치',
        badgeType: 'penalty',
        situation: '공이 완전히 밖으로 나갔습니다. 어디서 몇 타를 받고 쳐야 하나요?',
        parkyDialogue: '파크골프에는 1벌타 OB가 절대 없어요! 무조건 2벌타! 티박스로 돌아가지 않고 공이 나간 지점 코스 안쪽으로 홀에 가깝지 않게 2클럽 이내에 놓고 다음 타를 칩니다!',
        verdict: '【2벌타 가산】 후 OB 통과 지점 2클럽 이내 처치',
        penaltyText: 'OB 발생 시 무조건 2벌타 (1벌타 없음)',
        keyPoint: '티샷이 OB가 난 경우에도 나간 지점 2클럽에서 치는 샷이 제4타가 됩니다.',
        article: '제4장 제33조 제3항',
      },
    ],
  },
  'ch-5': {
    chapterId: 'ch-5',
    chapterNumber: '제5장',
    title: '워터 해저드와 무벌 구제',
    subtitle: '물에 빠진 공 2벌타와 배수구/카트도로 1클럽 무벌 구제',
    coverImage: '/mascot/사진저장고_사진_20260913_35.jpg',
    totalCuts: 2,
    cuts: [
      {
        cutNumber: 1,
        title: '워터 해저드(연못/개천)에 풍덩! 어떻게 하나요?',
        image: '/mascot/사진저장고_사진_20260913_35.jpg',
        badge: '2벌타 처치',
        badgeType: 'penalty',
        situation: '공이 워터 해저드 물이나 깊은 수로에 빠져 칠 수 없습니다.',
        parkyDialogue: '물이나 해저드에 빠지면 2벌타가 부과돼요! 공이 해저드 경계를 최종 통과한 지점에서 홀에 가깝지 않게 2클럽 이내 잔디에 놓고 다음 타를 치시면 됩니다!',
        verdict: '워터 해저드 침수 시 【2벌타 가산】',
        penaltyText: '2벌타 후 2클럽 이내 처치',
        keyPoint: '공이 물에 들어간 진입 지점을 기준으로 코스 내 2클럽 헤드 이내에 놓습니다.',
        article: '제5장 제34조 (워터 해저드 및 수리지) 제1항',
      },
      {
        cutNumber: 2,
        title: '배수구 쇠창살, 카트 도로는 1클럽 무벌 구제!',
        image: '/mascot/사진저장고_사진_20260913_36.jpg',
        badge: '무벌 구제',
        badgeType: 'safe',
        situation: '공이 배수구 철망 위나 아스팔트 카트 도로 위에 멈췄습니다.',
        parkyDialogue: '배수구 쇠창살, 아스팔트 카트 도로, 안전망 기둥은 인공 장해물이에요! 아까운 클럽 다치지 않게 홀에 가깝지 않은 잔디 구역으로 1클럽 이내에 무벌로 놓고 치세요!',
        verdict: '움직일 수 없는 인공 장해물 접촉 시 【무벌 1클럽 구제】',
        penaltyText: '벌타 없음 (무벌 구제)',
        keyPoint: '완전 구제 지점으로부터 홀에 가깝지 않은 1클럽 이내 잔디에 공을 놓습니다.',
        article: '제5장 제35조 (장해물) 제1항',
      },
    ],
  },
  'ch-6': {
    chapterId: 'ch-6',
    chapterNumber: '제6장',
    title: '그린과 퍼팅 규정',
    subtitle: '깃대 발거 금지 2벌타와 컵 테두리 걸친 공 판정',
    coverImage: '/mascot/사진저장고_사진_20260913_40.jpg',
    totalCuts: 2,
    cuts: [
      {
        cutNumber: 1,
        title: '깃대를 뽑고 퍼팅하면 2벌타?!',
        image: '/mascot/사진저장고_사진_20260913_40.jpg',
        badge: '2벌타 주의',
        badgeType: 'penalty',
        situation: '깃대가 방해된다며 홀컵에서 깃대를 뽑아 바닥에 내려놓고 쳤습니다.',
        parkyDialogue: '일반 골프와 가장 크게 다른 점! 파크골프는 안전과 신속한 경기 진행을 위해 어떤 경우에도 깃대를 뽑을 수 없어요! 깃대를 뽑거나 잡고 치면 2벌타를 받으니 꼭 꽂힌 상태로 치세요!',
        verdict: '깃대 임의 발거 후 퍼팅 시 【2벌타】',
        penaltyText: '깃대 발거 금지 위반 2벌타',
        keyPoint: '파크골프는 깃대를 뽑지 않고 꽂힌 상태로 홀아웃하는 것이 절대 원칙입니다.',
        article: '제6장 제37조 (홀아웃 및 깃대 규정) 제1항',
      },
      {
        cutNumber: 2,
        title: '공이 깃대와 컵 테두리 사이에 끼었어요!',
        image: '/mascot/사진저장고_사진_20260913_38.jpg',
        badge: '홀인 성공',
        badgeType: 'safe',
        situation: '퍼팅한 공이 깃대 봉과 홀 테두리 턱 사이에 끼어 바닥에 떨어지지 않았습니다.',
        parkyDialogue: '당황하지 마시고 동반자가 보는 앞에서 깃대를 조심스럽게 살짝 흔들어보세요! 공이 홀컵 바닥으로 쏙 떨어지면 직전 퍼팅으로 홀아웃 인정이랍니다!',
        verdict: '깃대 흔들어 바닥에 떨어지면 【홀인 인정】',
        penaltyText: '벌타 없음 (홀아웃 성공)',
        keyPoint: '동반자 입회 하에 깃대를 조심스럽게 움직여 바닥에 정지하면 성공입니다.',
        article: '제6장 제37조 제3항 (림 걸침 규정)',
      },
    ],
  },
  'ch-7': {
    chapterId: 'ch-7',
    chapterNumber: '제7장',
    title: '공 충돌과 벌타 총람',
    subtitle: '동반자 공 맞췄을 때 무벌과 남의 공 친 오구 2벌타',
    coverImage: '/mascot/사진저장고_사진_20260913_38.jpg',
    totalCuts: 2,
    cuts: [
      {
        cutNumber: 1,
        title: '내 공이 동반자의 정지된 공을 맞췄어요!',
        image: '/mascot/사진저장고_사진_20260913_38.jpg',
        badge: '친 사람 무벌',
        badgeType: 'safe',
        situation: '세컨샷이나 퍼팅을 했는데 앞에 서 있던 동반자의 공을 쾅 맞췄습니다.',
        parkyDialogue: '미안해하지 않으셔도 돼요! 친 분에게는 벌타가 전혀 없고 멈춘 곳에서 그대로 치시면 돼요! 맞아서 움직인 동반자의 공만 원래 있던 자리로 되돌려놓으면 된답니다!',
        verdict: '친 사람 【무벌】 / 맞은 공은 【원위치 리플레이스】',
        penaltyText: '벌타 없음 (무벌)',
        keyPoint: '충돌로 움직인 다른 플레이어의 공만 원래 위치로 리플레이스합니다.',
        article: '제7장 제36조 (공의 충돌 및 오구) 제1항',
      },
      {
        cutNumber: 2,
        title: '남의 공을 내 공인 줄 알고 쳤어요 (오구 플레이)',
        image: '/mascot/사진저장고_사진_20260913_29.jpg',
        badge: '2벌타 주의',
        badgeType: 'penalty',
        situation: '비슷한 색깔의 동반자 공을 내 공인 줄 착각하고 풀스윙으로 쳤습니다.',
        parkyDialogue: '비슷한 공이라도 방심은 금물! 남의 공을 치는 오구 플레이는 2벌타예요! 잘못 친 공은 즉시 제자리로 돌려놓고, 본인의 진짜 공을 찾아 원래 자리에서 치셔야 해요!',
        verdict: '오구 플레이 위반으로 【2벌타 가산】',
        penaltyText: '2벌타 부과',
        keyPoint: '잘못 친 공은 즉시 원위치하고, 2벌타 가산 후 본인 공으로 재개합니다.',
        article: '제7장 제36조 제2항',
      },
    ],
  },
  'ch-8': {
    chapterId: 'ch-8',
    chapterNumber: '제8장',
    title: '스코어 기록과 경기 매너',
    subtitle: '컨시드(OK) 절대 불가와 안전거리 확보',
    coverImage: '/mascot/사진저장고_사진_20260913_28.jpg',
    totalCuts: 2,
    cuts: [
      {
        cutNumber: 1,
        title: '파크골프에는 "오케이(컨시드)"가 절대 없어요!',
        image: '/mascot/사진저장고_사진_20260913_28.jpg',
        badge: '실격 주의',
        badgeType: 'penalty',
        situation: '홀컵 10cm 앞에 멈춰서 당연히 들어갈 줄 알고 집은 뒤 다음 홀로 갔습니다.',
        parkyDialogue: '파크골프는 아무리 10cm 짧은 거리라도 "오케이(컨시드)"가 없어요! 컵 바닥에 떨어져 땡그랑 소리를 들을 때까지 쳐야 해요! 안 넣고 다음 홀로 가면 실격 처리된답니다!',
        verdict: '홀아웃 미완료 상태로 다음 홀 티샷 시 【실격】',
        penaltyText: '실격 (Disqualified)',
        keyPoint: '반드시 공이 홀컵 바닥에 멈출 때까지 스트로크를 마쳐야 합니다.',
        article: '제8장 제37조 제4항 & 제45조',
      },
      {
        cutNumber: 2,
        title: '앞 조가 이동하기 전에 치면 절대 안 돼요!',
        image: '/mascot/사진저장고_사진_20260913_34.jpg',
        badge: '안전 에티켓',
        badgeType: 'caution',
        situation: '앞 조가 아직 페어웨이에 서 있는데 뒤에서 그대로 티샷을 날렸습니다.',
        parkyDialogue: '파크골프 공은 매우 단단해서 맞으면 큰 부상으로 이어져요! 앞 조 분들이 완전히 다음 홀 안전지대로 이동한 것을 확인한 뒤에만 티샷해야 해요! 위반 시 2벌타나 퇴장이에요!',
        verdict: '안전거리 미확보 타격 시 【2벌타 또는 실격】',
        penaltyText: '안전 수칙 위반 2벌타',
        keyPoint: '전방 경기자의 안전거리가 완전히 확보된 후에만 스트로크합니다.',
        article: '제8장 제50조 (안전 수칙 및 매너)',
      },
    ],
  },
};
