import { ParkGolfClub } from '@/types/club';

// 전국 지역별 실제 파크골프 클럽 & 온라인 활동 동호회 디렉토리 데이터
export const NATIONWIDE_PARKGOLF_CLUBS: ParkGolfClub[] = [
  // ========================================================
  // 1. 경북 구미시 (Gumi)
  // ========================================================
  {
    id: 'club-gumi-dongrak',
    name: '구미 동락 에이스 파크골프 클럽',
    region: '경북 구미',
    homeCourseId: 'course-gumi-dongrak',
    homeCourseName: '구미 동락 파크골프장 (36홀)',
    description: '구미 동락구장을 홈으로 활동하는 파크온 공식 1호 명문 클럽! 매월 정기 월례회 및 친선 대항전 활성화.',
    presidentName: '박회장',
    managerName: '김총무',
    contactPhone: '010-3814-1422',
    memberCount: 64,
    members: [
      { id: 'm_pres_1', name: '박회장', role: 'PRESIDENT', joinedAt: '2026-01-01' },
      { id: 'm_mgr_1', name: '김총무', role: 'MANAGER', joinedAt: '2026-01-05' },
    ],
    pendingMembers: [],
    isPublic: true,
    badgeColor: 'emerald',
    isParkOnClub: true,
    recruitStatus: 'RECRUITING',
    recruitQuota: 8,
    recruitNotes: '주말 오전 동락 36홀 정기 라운드 동반 단원 선착순 8명 모집 중입니다.',
    createdAt: '2026-01-01',
  },
  {
    id: 'club-gumi-seonsan',
    name: '구미 선산 낙동강 파크골프 클럽',
    region: '경북 구미',
    homeCourseId: 'course-gumi-seonsan',
    homeCourseName: '구미 선산 파크골프장 (27홀)',
    description: '낙동강변 선산구장에서 매주 주말 정기 번개 및 클럽 대항전을 펼치는 파크온 공식 등록 클럽입니다.',
    presidentName: '이선산',
    managerName: '최총무',
    contactPhone: '010-9876-5432',
    memberCount: 48,
    members: [
      { id: 'm_pres_2', name: '이선산', role: 'PRESIDENT', joinedAt: '2026-02-10' },
      { id: 'm_mgr_2', name: '최총무', role: 'MANAGER', joinedAt: '2026-02-12' },
    ],
    pendingMembers: [],
    isPublic: true,
    badgeColor: 'amber',
    isParkOnClub: true,
    recruitStatus: 'RECRUITING',
    recruitQuota: 5,
    recruitNotes: '선산구장 정기 타수 향상 및 친선 라운드 동반자 5명 모집!',
    createdAt: '2026-02-10',
  },
  {
    id: 'club-gumi-yangho-dopamine',
    name: '구미 양호 도파민 파크골프 클럽',
    region: '경북 구미',
    homeCourseId: 'course-gumi-yangho',
    homeCourseName: '구미 양포(양호) 파크골프장',
    description: '양호구장에서 매일 즐겁고 활기차게 라운드하는 젊은 감각의 파크온 공식 제휴 클럽입니다.',
    presidentName: '채회장',
    managerName: '양총무',
    contactPhone: '010-2222-3333',
    memberCount: 28,
    members: [],
    pendingMembers: [],
    isPublic: true,
    badgeColor: 'purple',
    isParkOnClub: true,
    recruitStatus: 'ALWAYS',
    recruitNotes: '양호구장을 사랑하는 골퍼라면 누구나 상시 환영합니다!',
    createdAt: '2026-02-15',
  },
  {
    id: 'club-gumi-bisan-local',
    name: '구미 비산 강변 파크골프 동호회',
    region: '경북 구미',
    homeCourseId: 'course-gumi-dongrak',
    homeCourseName: '구미 비산 체육공원 파크골프장',
    description: '비산 체육공원 인근 주민 자생 파크골프 친목 모임입니다.',
    presidentName: '김비산',
    managerName: '박총무',
    memberCount: 35,
    members: [],
    isPublic: true,
    isParkOnClub: false,
    recruitStatus: 'ALWAYS',
    createdAt: '2026-03-01',
  },
  {
    id: 'club-gumi-dogae-local',
    name: '구미 도개 파크골프 사랑회',
    region: '경북 구미',
    homeCourseId: 'course-gumi-dongrak',
    homeCourseName: '구미 도개 파크골프장',
    description: '도개면 주민 및 어르신 건강 증진 친목 파크골프 동호회입니다.',
    presidentName: '이도개',
    managerName: '한총무',
    memberCount: 26,
    members: [],
    isPublic: true,
    isParkOnClub: false,
    recruitStatus: 'CLOSED',
    createdAt: '2026-03-05',
  },
  {
    id: 'club-gumi-haepyeong',
    name: '구미 해평 낙동 파크골프 클럽',
    region: '경북 구미',
    homeCourseId: 'course-gumi-seonsan',
    homeCourseName: '구미 해평 파크골프장',
    description: '해평 철새 도래지 인근 수려한 낙동강 코스에서 활동하는 동호회입니다.',
    presidentName: '정해평',
    managerName: '송총무',
    memberCount: 31,
    members: [],
    isPublic: true,
    isParkOnClub: false,
    recruitStatus: 'ALWAYS',
    createdAt: '2026-03-08',
  },
  {
    id: 'club-gumi-geumo',
    name: '구미 금오산 파크골프 동우회',
    region: '경북 구미',
    homeCourseId: 'course-gumi-dongrak',
    homeCourseName: '구미 동락 / 금오산권 파크골프장',
    description: '금오산의 정기를 받아 정정당당한 매너 라운드를 지향하는 친목 모임입니다.',
    presidentName: '강금오',
    managerName: '임총무',
    memberCount: 42,
    members: [],
    isPublic: true,
    isParkOnClub: false,
    recruitStatus: 'SCHEDULED',
    recruitTargetDate: '2026년 10월 가을 정기 모집 예정',
    createdAt: '2026-03-10',
  },
  {
    id: 'club-gumi-bonggok',
    name: '구미 봉곡 파크골프 친목회',
    region: '경북 구미',
    homeCourseId: 'course-gumi-dongrak',
    homeCourseName: '구미 동락 파크골프장',
    description: '봉곡동, 도량동 주민 중심의 친목 파크골프 모임입니다.',
    presidentName: '윤봉곡',
    managerName: '배총무',
    memberCount: 29,
    members: [],
    isPublic: true,
    isParkOnClub: false,
    recruitStatus: 'ALWAYS',
    createdAt: '2026-03-12',
  },
  {
    id: 'club-gumi-indong',
    name: '구미 인동 만남 파크골프 클럽',
    region: '경북 구미',
    homeCourseId: 'course-gumi-dongrak',
    homeCourseName: '구미 동락 파크골프장',
    description: '인동, 진평권 직장인 및 자영업자 파크골프 주말 동호회입니다.',
    presidentName: '문인동',
    managerName: '신총무',
    memberCount: 38,
    members: [],
    isPublic: true,
    isParkOnClub: false,
    recruitStatus: 'CLOSED',
    createdAt: '2026-03-15',
  },
  {
    id: 'club-gumi-okgye',
    name: '구미 옥계 한빛 파크골프 클럽',
    region: '경북 구미',
    homeCourseId: 'course-gumi-yangho',
    homeCourseName: '구미 양호 파크골프장',
    description: '옥계 4공단 인근 주민들이 함께 모여 라운드를 즐기는 클럽입니다.',
    presidentName: '조옥계',
    managerName: '황총무',
    memberCount: 34,
    members: [],
    isPublic: true,
    isParkOnClub: false,
    recruitStatus: 'ALWAYS',
    createdAt: '2026-03-16',
  },
  {
    id: 'club-gumi-hyeonggok',
    name: '구미 형곡 한마음 파크골프회',
    region: '경북 구미',
    homeCourseId: 'course-gumi-dongrak',
    homeCourseName: '구미 동락 파크골프장',
    description: '형곡동 어르신 및 중장년층 친목 도모를 위한 생활체육 모임입니다.',
    presidentName: '서형곡',
    managerName: '남총무',
    memberCount: 27,
    members: [],
    isPublic: true,
    isParkOnClub: false,
    recruitStatus: 'CLOSED',
    createdAt: '2026-03-18',
  },
  {
    id: 'club-gumi-jisan',
    name: '구미 지산 샛강 파크골프 동호회',
    region: '경북 구미',
    homeCourseId: 'course-gumi-dongrak',
    homeCourseName: '구미 동락 파크골프장',
    description: '지산 샛강 생태공원 인근 골퍼들의 친목 커뮤니티입니다.',
    presidentName: '고지산',
    managerName: '안총무',
    memberCount: 22,
    members: [],
    isPublic: true,
    isParkOnClub: false,
    recruitStatus: 'ALWAYS',
    createdAt: '2026-03-20',
  },
  {
    id: 'club-gumi-cheongsol',
    name: '구미 청솔 파크골프 클럽',
    region: '경북 구미',
    homeCourseId: 'course-gumi-dongrak',
    homeCourseName: '구미 동락 파크골프장',
    description: '푸른 솔처럼 건강하고 활기찬 라운드를 함께하는 구미 명문 동호회입니다.',
    presidentName: '유청솔',
    managerName: '류총무',
    memberCount: 45,
    members: [],
    isPublic: true,
    isParkOnClub: false,
    recruitStatus: 'SCHEDULED',
    recruitTargetDate: '2026년 10월 중 모집 공고 예정',
    createdAt: '2026-03-22',
  },

  // ========================================================
  // 2. 대구광역시 (Daegu)
  // ========================================================
  {
    id: 'club-daegu-suseong',
    name: '대구 수성 범어 파크골프 클럽',
    region: '대구 수성',
    homeCourseId: 'course-daegu-suseong',
    homeCourseName: '대구 수성 파크골프장',
    description: '대구 수성구를 대표하는 명문 클럽! 파크온 실시간 대회 스코어링 및 신페리오 샷건 대회 공식 운영.',
    presidentName: '정수성',
    managerName: '강총무',
    contactPhone: '010-5555-4444',
    memberCount: 52,
    members: [],
    pendingMembers: [],
    isPublic: true,
    badgeColor: 'blue',
    isParkOnClub: true,
    recruitStatus: 'RECRUITING',
    recruitQuota: 12,
    recruitNotes: '수성구장 가을 친선 대회 대비 신규 단원 12명 선착순 모집!',
    createdAt: '2026-01-15',
  },
  {
    id: 'club-daegu-dasa',
    name: '대구 달성 다사 파크골프 클럽',
    region: '대구 달성',
    homeCourseId: 'course-daegu-gangchang',
    homeCourseName: '대구 강창 파크골프장',
    description: '강창교 금호강 둔치 명품 코스에서 활동하는 파크온 공식 등록 클럽입니다.',
    presidentName: '김다사',
    managerName: '박총무',
    contactPhone: '010-4444-3333',
    memberCount: 39,
    members: [],
    pendingMembers: [],
    isPublic: true,
    badgeColor: 'emerald',
    isParkOnClub: true,
    recruitStatus: 'SCHEDULED',
    recruitTargetDate: '2026년 10월 정기 모집 예정',
    createdAt: '2026-02-18',
  },
  {
    id: 'club-daegu-gangchang-local',
    name: '대구 강창 파크골프 동호회',
    region: '대구 달서',
    homeCourseId: 'course-daegu-gangchang',
    homeCourseName: '대구 강창 파크골프장',
    description: '달서구 및 달성군 주민 친목 파크골프 모임입니다.',
    presidentName: '이강창',
    managerName: '최총무',
    memberCount: 46,
    members: [],
    isPublic: true,
    isParkOnClub: false,
    recruitStatus: 'ALWAYS',
    createdAt: '2026-03-01',
  },
  {
    id: 'club-daegu-chimsan',
    name: '대구 침산 금호강 파크골프회',
    region: '대구 북구',
    homeCourseId: 'course-daegu-chimsan',
    homeCourseName: '대구 북구 금호강 파크골프장',
    description: '북구 침산동 금호강변 코스에서 매일 오전 활동하는 건강 동호회입니다.',
    presidentName: '조침산',
    managerName: '윤총무',
    memberCount: 33,
    members: [],
    isPublic: true,
    isParkOnClub: false,
    recruitStatus: 'ALWAYS',
    createdAt: '2026-03-05',
  },
  {
    id: 'club-daegu-dongchon',
    name: '대구 동촌 유원지 파크골프 사랑방',
    region: '대구 동구',
    homeCourseId: 'course-daegu-dongchon',
    homeCourseName: '대구 동구 불로·동촌 파크골프장',
    description: '동촌 유원지 맑은 공기 속에서 친목 라운드를 나누는 모임입니다.',
    presidentName: '오동촌',
    managerName: '하총무',
    memberCount: 28,
    members: [],
    isPublic: true,
    isParkOnClub: false,
    recruitStatus: 'CLOSED',
    createdAt: '2026-03-10',
  },

  // ========================================================
  // 3. 부산광역시 (Busan)
  // ========================================================
  {
    id: 'club-busan-samrak',
    name: '부산 삼락 센텀 파크골프 클럽',
    region: '부산 사상',
    homeCourseId: 'course-busan-samrak',
    homeCourseName: '부산 삼락 생태공원 파크골프장 (36홀)',
    description: '부산 삼락 생태공원 36홀 명품 코스에서 활동하는 남부권 최대 파크온 제휴 명문 클럽입니다.',
    presidentName: '오삼락',
    managerName: '윤총무',
    contactPhone: '010-7777-8888',
    memberCount: 76,
    members: [],
    pendingMembers: [],
    isPublic: true,
    badgeColor: 'purple',
    isParkOnClub: true,
    recruitStatus: 'RECRUITING',
    recruitQuota: 15,
    recruitNotes: '삼락 36홀 주말 대회 출전 엔트리 단원 15명 모집 중!',
    createdAt: '2026-01-10',
  },
  {
    id: 'club-busan-hwamyeong',
    name: '부산 화명 생태 파크골프 클럽',
    region: '부산 북구',
    homeCourseId: 'course-busan-hwamyeong',
    homeCourseName: '부산 화명 생태공원 파크골프장',
    description: '낙동강 하구 화명 생태공원에서 활동하는 파크온 인증 클럽입니다.',
    presidentName: '정화명',
    managerName: '문총무',
    contactPhone: '010-8888-9999',
    memberCount: 54,
    members: [],
    pendingMembers: [],
    isPublic: true,
    badgeColor: 'emerald',
    isParkOnClub: true,
    recruitStatus: 'ALWAYS',
    recruitNotes: '북구/사상구 거주 동호인 상시 환영!',
    createdAt: '2026-02-05',
  },
  {
    id: 'club-busan-daejeo',
    name: '부산 대저 생태공원 파크골프회',
    region: '부산 강서',
    homeCourseId: 'course-busan-daejeo',
    homeCourseName: '부산 대저 파크골프장',
    description: '유채꽃 만발하는 대저 생태공원에서 친목을 도모하는 동호회입니다.',
    presidentName: '김대저',
    managerName: '송총무',
    memberCount: 41,
    members: [],
    isPublic: true,
    isParkOnClub: false,
    recruitStatus: 'ALWAYS',
    createdAt: '2026-03-02',
  },
  {
    id: 'club-busan-eulsukdo',
    name: '부산 을숙도 낙조 파크골프 클럽',
    region: '부산 사하',
    homeCourseId: 'course-busan-eulsukdo',
    homeCourseName: '부산 을숙도 파크골프장',
    description: '을숙도 낙조를 바라보며 매너 라운드를 즐기는 동호회입니다.',
    presidentName: '배을숙',
    managerName: '안총무',
    memberCount: 36,
    members: [],
    isPublic: true,
    isParkOnClub: false,
    recruitStatus: 'CLOSED',
    createdAt: '2026-03-07',
  },

  // ========================================================
  // 4. 서울특별시 / 수도권 (Seoul / Gyeonggi)
  // ========================================================
  {
    id: 'club-seoul-hangang',
    name: '서울 한강 월드 파크골프 클럽',
    region: '서울 영등포',
    homeCourseId: 'course-seoul-yeouido',
    homeCourseName: '여의도 한강 파크골프장',
    description: '수도권 한강변 코스를 사랑하는 골퍼들의 파크온 공식 등록 클럽입니다.',
    presidentName: '최한강',
    managerName: '조총무',
    contactPhone: '010-6666-1111',
    memberCount: 65,
    members: [],
    pendingMembers: [],
    isPublic: true,
    badgeColor: 'blue',
    isParkOnClub: true,
    recruitStatus: 'RECRUITING',
    recruitQuota: 10,
    recruitNotes: '수도권 주말 한강 정기 라운드 단원 10명 선착순 모집!',
    createdAt: '2026-02-20',
  },
  {
    id: 'club-seoul-yeouido-par',
    name: '서울 여의도 파크골프 사랑방',
    region: '서울 영등포',
    homeCourseId: 'course-seoul-yeouido',
    homeCourseName: '여의도 한강 파크골프장',
    description: '영등포 및 마포구 주민 친목 파크골프 커뮤니티입니다.',
    presidentName: '한여의',
    managerName: '구총무',
    memberCount: 48,
    members: [],
    isPublic: true,
    isParkOnClub: false,
    recruitStatus: 'ALWAYS',
    createdAt: '2026-03-01',
  },
  {
    id: 'club-seoul-jamsil',
    name: '서울 잠실 탄천 파크골프회',
    region: '서울 송파',
    homeCourseId: 'course-seoul-jamsil',
    homeCourseName: '잠실 파크골프장',
    description: '송파구 잠실 탄천변에서 활동하는 강남권 친목 동호회입니다.',
    presidentName: '서잠실',
    managerName: '백총무',
    memberCount: 52,
    members: [],
    isPublic: true,
    isParkOnClub: false,
    recruitStatus: 'SCHEDULED',
    recruitTargetDate: '2026년 10월 공고 예정',
    createdAt: '2026-03-05',
  },

  // ========================================================
  // 5. 경남 / 경북 기타 (Gyeongnam / Gyeongbuk)
  // ========================================================
  {
    id: 'club-gyeongnam-gimhae',
    name: '김해 가야 파크골프 클럽',
    region: '경남 김해',
    homeCourseId: 'course-gimhae-gaya',
    homeCourseName: '김해 조만강 파크골프장',
    description: '가야 왕도의 유서 깊은 조만강 코스에서 활약하는 파크온 공식 클럽입니다.',
    presidentName: '김가야',
    managerName: '구총무',
    contactPhone: '010-3333-7777',
    memberCount: 45,
    members: [],
    pendingMembers: [],
    isPublic: true,
    badgeColor: 'amber',
    isParkOnClub: true,
    recruitStatus: 'RECRUITING',
    recruitQuota: 8,
    recruitNotes: '경남권 정기 교류전 선수단 8명 모집!',
    createdAt: '2026-02-25',
  },
  {
    id: 'club-pohang-hyeongsangang',
    name: '포항 형산강 파크골프 클럽',
    region: '경북 포항',
    homeCourseId: 'course-pohang-hyeongsan',
    homeCourseName: '포항 형산강 파크골프장',
    description: '동해 바다와 형산강이 만나는 시원한 코스의 파크온 제휴 클럽입니다.',
    presidentName: '포형산',
    managerName: '강총무',
    contactPhone: '010-1111-9999',
    memberCount: 49,
    members: [],
    pendingMembers: [],
    isPublic: true,
    badgeColor: 'emerald',
    isParkOnClub: true,
    recruitStatus: 'RECRUITING',
    recruitQuota: 6,
    recruitNotes: '포항 형산강 주말 친선 라운드 동반 단원 6명 모집!',
    createdAt: '2026-02-22',
  },
  {
    id: 'club-gyeongju-alcheon',
    name: '경주 알천 파크골프 동호회',
    region: '경북 경주',
    homeCourseId: 'course-gyeongju-alcheon',
    homeCourseName: '경주 알천 파크골프장',
    description: '천년고도 경주 알천변에서 매너와 화합을 다지는 동호회입니다.',
    presidentName: '신경주',
    managerName: '문총무',
    memberCount: 37,
    members: [],
    isPublic: true,
    isParkOnClub: false,
    recruitStatus: 'ALWAYS',
    createdAt: '2026-03-04',
  },
  {
    id: 'club-gimcheon-innov',
    name: '김천 혁신 파크골프 클럽',
    region: '경북 김천',
    homeCourseId: 'course-gimcheon-gangbyeon',
    homeCourseName: '김천 감천 파크골프장',
    description: '김천 혁신도시 이전 공공기관 임직원 및 주민 친선 동호회입니다.',
    presidentName: '류김천',
    managerName: '손총무',
    memberCount: 32,
    members: [],
    isPublic: true,
    isParkOnClub: false,
    recruitStatus: 'CLOSED',
    createdAt: '2026-03-08',
  },
];
