import { Course, HoleMetadata, DisputeRule } from '@/types/parkon';

export function generateStandardHoles(totalHoles: number = 18): HoleMetadata[] {
  const holes: HoleMetadata[] = [];
  // Typical 9-hole pattern: 4x Par 3, 4x Par 4, 1x Par 5 -> 33 Par
  const parPattern = [3, 4, 3, 4, 5, 4, 3, 4, 3];
  const distancePattern = [45, 65, 40, 75, 120, 80, 50, 70, 45];
  for (let i = 1; i <= totalHoles; i++) {
    const patternIdx = (i - 1) % 9;
    const par = parPattern[patternIdx];
    const dist = distancePattern[patternIdx];
    holes.push({
      hole: i,
      par,
      distanceMeter: dist,
      localRule: undefined,
      tip: undefined,
    });
  }
  return holes;
}

export const DEFAULT_COURSES: Course[] = [
  // ==================== 경북 구미시 (파크골프 메카) ====================
  {
    id: 'course-gumi-dongrak',
    name: '구미 동락 파크골프장',
    region: '경북 구미시 진평동',
    totalCourses: 4,
    totalHoles: 36,
    isVerified: true,
    description: '낙동강 둔치에 위치한 경북 대표 총 4코스 36홀 명문 공인 구장',
    contributorName: '구미파크골프협회',
    contributedAt: '2026-09-10',
    holesMetadata: generateStandardHoles(36),
  },
  {
    id: 'course-gumi-yangho',
    name: '구미 양호 파크골프장',
    region: '경북 구미시 양호동',
    totalCourses: 4,
    totalHoles: 36,
    isVerified: true,
    description: '금오공대 인근 낙동강 수변에 조성된 쾌적한 총 4코스 36홀 잔디 구장',
    contributorName: '양호클럽마스터',
    contributedAt: '2026-09-08',
    holesMetadata: generateStandardHoles(36),
  },
  {
    id: 'course-gumi-jisan',
    name: '구미 지산 파크골프장',
    region: '경북 구미시 지산동',
    totalCourses: 7,
    totalHoles: 63,
    isVerified: true,
    description: '지산 샛강 생태공원에 펼쳐진 총 7코스 63홀의 웅장한 공인 천연잔디 구장',
    contributorName: '지산사랑',
    contributedAt: '2026-09-07',
    holesMetadata: generateStandardHoles(63),
  },
  {
    id: 'course-gumi-seonsan',
    name: '구미 선산 파크골프장',
    region: '경북 구미시 선산읍',
    totalCourses: 2,
    totalHoles: 18,
    isVerified: true,
    description: '선산 감천 둔치의 천연 잔디와 울창한 나무 그늘이 있는 총 2코스 18홀 구장',
    contributorName: '선산골퍼',
    contributedAt: '2026-09-05',
    holesMetadata: generateStandardHoles(18),
  },
  {
    id: 'course-gumi-dogae',
    name: '구미 도개 파크골프장',
    region: '경북 구미시 도개면',
    totalCourses: 2,
    totalHoles: 18,
    isVerified: true,
    description: '도개면 낙동강변의 탁 트인 시야와 넓은 페어웨이를 자랑하는 총 2코스 18홀 코스',
    holesMetadata: generateStandardHoles(18),
  },
  {
    id: 'course-gumi-haepyeong',
    name: '구미 해평 파크골프장',
    region: '경북 구미시 해평면',
    totalCourses: 1,
    totalHoles: 9,
    isVerified: true,
    description: '해평 철새도래지 인근의 아늑한 총 1코스 9홀 로컬 코스',
    holesMetadata: generateStandardHoles(9),
  },
  {
    id: 'course-gumi-okseong',
    name: '구미 옥성 파크골프장',
    region: '경북 구미시 옥성면',
    totalCourses: 2,
    totalHoles: 18,
    isVerified: true,
    description: '옥성 자연휴양림 방향 낙동강 수변에 확장 조성된 쾌적한 총 2코스 18홀 코스',
    holesMetadata: generateStandardHoles(18),
  },
  {
    id: 'course-gumi-seongrihak',
    name: '구미 성리학 파크골프장',
    region: '경북 구미시 남통동 (금오산)',
    totalCourses: 2,
    totalHoles: 18,
    isVerified: true,
    description: '금오산 성리학역사관 인근에 위치한 쾌적한 총 2코스 18홀 파크골프장',
    holesMetadata: generateStandardHoles(18),
  },
  {
    id: 'course-gumi-cc',
    name: '구미CC 파크골프장',
    region: '경북 구미시 산동읍',
    totalCourses: 4,
    totalHoles: 36,
    isVerified: true,
    description: '구미 산동에 위치한 명문 총 4코스 36홀 파크골프 코스',
    holesMetadata: generateStandardHoles(36),
  },

  // ==================== 대구광역시 ====================
  {
    id: 'course-daegu-suseong',
    name: '수성 패밀리 파크골프장',
    region: '대구 수성구 고모동',
    totalHoles: 18,
    isVerified: true,
    description: '금호강 둔치에 조성된 가족 친화형 인기 18홀 구장',
    contributorName: '수성패밀리총무',
    holesMetadata: generateStandardHoles(18),
  },
  {
    id: 'course-daegu-gangbyeon',
    name: '대구 강변 파크골프장',
    region: '대구 북구 검단동',
    totalHoles: 27,
    isVerified: true,
    description: '대구 북구 금호강변의 대표적인 27홀 파크골프장',
    holesMetadata: generateStandardHoles(27),
  },
  {
    id: 'course-daegu-dasa',
    name: '달성군 다사 파크골프장',
    region: '대구 달성군 다사읍',
    totalHoles: 36,
    isVerified: true,
    description: '강정보 디아크 인근 낙동강 수변의 36홀 대규모 코스',
    holesMetadata: generateStandardHoles(36),
  },
  {
    id: 'course-daegu-secheon',
    name: '대구 세천 파크골프장',
    region: '대구 달성군 다사읍 세천리',
    totalHoles: 18,
    isVerified: true,
    description: '금호강변 자전거길과 접한 조용하고 정비가 잘된 18홀 구장',
    holesMetadata: generateStandardHoles(18),
  },
  {
    id: 'course-daegu-bisan',
    name: '대구 비산 파크골프장',
    region: '대구 서구 비산동',
    totalHoles: 18,
    isVerified: true,
    description: '대구 서구 주민들의 사랑을 받는 도심 속 18홀 구장',
    holesMetadata: generateStandardHoles(18),
  },
  {
    id: 'course-daegu-bullo',
    name: '대구 불로 파크골프장',
    region: '대구 동구 불로동',
    totalHoles: 18,
    isVerified: true,
    description: '금호강 둔치 불로천 합류부에 위치한 18홀 구장',
    holesMetadata: generateStandardHoles(18),
  },

  // ==================== 경상북도 (포항, 경주, 안동, 칠곡 등) ====================
  {
    id: 'course-pohang-hyeongsan',
    name: '포항 형산강 파크골프장',
    region: '경북 포항시 남구 효자동',
    totalHoles: 36,
    isVerified: true,
    description: '형산강 수변 공원에 조성된 포항 대표 36홀 잔디 구장',
    holesMetadata: generateStandardHoles(36),
  },
  {
    id: 'course-gyeongju-seocheon',
    name: '경주 서천 파크골프장',
    region: '경북 경주시 황성동',
    totalHoles: 18,
    isVerified: true,
    description: '서천둔치 형산강변의 수려한 경관과 함께하는 18홀 코스',
    holesMetadata: generateStandardHoles(18),
  },
  {
    id: 'course-andong-nakdong',
    name: '안동 낙동강 파크골프장',
    region: '경북 안동시 정상동',
    totalHoles: 36,
    isVerified: true,
    description: '영가대교 아래 낙동강 둔치에 펼쳐진 36홀 명문 코스',
    holesMetadata: generateStandardHoles(36),
  },
  {
    id: 'course-chilgok-seokjeok',
    name: '칠곡 석적 파크골프장',
    region: '경북 칠곡군 석적읍',
    totalHoles: 18,
    isVerified: true,
    description: '구미와 인접한 칠곡보 인근 낙동강 18홀 코스',
    holesMetadata: generateStandardHoles(18),
  },
  {
    id: 'course-gimcheon-gamcheon',
    name: '김천 감천 파크골프장',
    region: '경북 김천시 감천면',
    totalHoles: 18,
    isVerified: true,
    description: '김천 혁신도시 및 감천 둔치에 조성된 친환경 18홀 구장',
    holesMetadata: generateStandardHoles(18),
  },
  {
    id: 'course-mungyeong-yeonggang',
    name: '문경 영강 파크골프장',
    region: '경북 문경시 점촌동',
    totalCourses: 2,
    totalHoles: 18,
    isVerified: true,
    description: '영강체육공원 내에 위치한 천연잔디 총 2코스 18홀 구장',
    holesMetadata: generateStandardHoles(18),
  },
  {
    id: 'course-uiseong-108',
    name: '의성 파크골프장',
    region: '경북 의성군 의성읍',
    totalCourses: 12,
    totalHoles: 108,
    isVerified: true,
    description: '국내 최대 규모 총 12코스 108홀의 초대형 명문 파크골프 파라다이스',
    contributorName: '의성군파크골프협회',
    contributedAt: '2026-09-11',
    holesMetadata: generateStandardHoles(108),
  },
  {
    id: 'course-cheongsong-juwangsan',
    name: '청송 주왕산 파크골프장',
    region: '경북 청송군 청송읍',
    totalCourses: 2,
    totalHoles: 18,
    isVerified: true,
    description: '주왕산 기슭과 용전천 맑은 물줄기를 따라 조성된 18홀 천연잔디 구장',
    contributorName: '청송파크골프클럽',
    contributedAt: '2026-09-11',
    holesMetadata: generateStandardHoles(18),
  },

  // ==================== 서울 / 수도권 ====================
  {
    id: 'course-seoul-hangang',
    name: '여의도 한강 파크골프장',
    region: '서울 영등포구 여의도동',
    totalHoles: 18,
    isVerified: true,
    description: '63빌딩 앞 한강둔치 18홀 코스 (예약제 운영)',
    holesMetadata: generateStandardHoles(18),
  },
  {
    id: 'course-songpa-jamsil',
    name: '잠실 파크골프장',
    region: '서울 송파구 잠실동',
    totalHoles: 18,
    isVerified: true,
    description: '잠실종합운동장 한강공원에 위치한 도심형 인기 코스',
    holesMetadata: generateStandardHoles(18),
  },
  {
    id: 'course-seoul-nanji',
    name: '월드컵공원 난지 파크골프장',
    region: '서울 마포구 상암동',
    totalHoles: 18,
    isVerified: true,
    description: '난지한강공원 잔디마당에 조성된 18홀 코스',
    holesMetadata: generateStandardHoles(18),
  },
  {
    id: 'course-yangpyeong-gangsang',
    name: '양평 강상 파크골프장',
    region: '경기 양평군 강상면',
    totalHoles: 36,
    isVerified: true,
    description: '남한강변에 위치한 수도권 최대 규모 36홀 명문 구장',
    holesMetadata: generateStandardHoles(36),
  },
  {
    id: 'course-gapyeong-jaraseom',
    name: '가평 자라섬 파크골프장',
    region: '경기 가평군 가평읍',
    totalHoles: 18,
    isVerified: true,
    description: '북한강 자라섬의 아름다운 자연경관 속 18홀 코스',
    holesMetadata: generateStandardHoles(18),
  },
  {
    id: 'course-seongnam-tancheon',
    name: '성남 탄천 파크골프장',
    region: '경기 성남시 분당구',
    totalHoles: 18,
    isVerified: true,
    description: '분당 탄천 수변공원을 따라 길게 조성된 18홀 구장',
    holesMetadata: generateStandardHoles(18),
  },
  {
    id: 'course-hwaseong-dongtan',
    name: '화성 동탄 파크골프장',
    region: '경기 화성시 동탄',
    totalHoles: 18,
    isVerified: true,
    description: '동탄 신도시 치동천 수변공원 인근의 정비된 18홀 코스',
    holesMetadata: generateStandardHoles(18),
  },

  // ==================== 부산 / 경남 ====================
  {
    id: 'course-busan-samnak',
    name: '삼락 생태공원 파크골프장',
    region: '부산 사상구 삼락동',
    totalHoles: 36,
    isVerified: true,
    description: '낙동강변 삼락생태공원 내 36홀 전국구 파크골프장',
    holesMetadata: generateStandardHoles(36),
  },
  {
    id: 'course-busan-daejeo',
    name: '대저 생태공원 파크골프장',
    region: '부산 강서구 대저1동',
    totalHoles: 36,
    isVerified: true,
    description: '유채꽃밭과 낙동강 둔치가 어우러진 36홀 명문 코스',
    holesMetadata: generateStandardHoles(36),
  },
  {
    id: 'course-changwon-daesan',
    name: '창원 대산 파크골프장',
    region: '경남 창원시 의창구 대산면',
    totalHoles: 72,
    isVerified: true,
    description: '국내 최대 72홀 규모를 자랑하는 전국 파크골프 성지',
    holesMetadata: generateStandardHoles(72),
  },
  {
    id: 'course-miryang-arirang',
    name: '밀양 아리랑 파크골프장',
    region: '경남 밀양시 삼문동',
    totalHoles: 45,
    isVerified: true,
    description: '밀양강 삼문송림 수변에 펼쳐진 45홀 대규모 코스',
    holesMetadata: generateStandardHoles(45),
  },
  {
    id: 'course-yangsan-hwangsan',
    name: '양산 황산 파크골프장',
    region: '경남 양산시 물금읍',
    totalHoles: 36,
    isVerified: true,
    description: '황산문화체육공원 내 낙동강변 36홀 명품 코스',
    holesMetadata: generateStandardHoles(36),
  },

  // ==================== 충청 / 전라 / 강원 / 제주 ====================
  {
    id: 'course-sejong-geumgang',
    name: '세종 금강 파크골프장',
    region: '세종특별자치시 대평동',
    totalHoles: 36,
    isVerified: true,
    description: '금강변 수변공원에 조성된 세종시 공인 36홀 코스',
    holesMetadata: generateStandardHoles(36),
  },
  {
    id: 'course-chungju-mokgye',
    name: '충주 목계 파크골프장',
    region: '충북 충주시 엄정면',
    totalHoles: 36,
    isVerified: true,
    description: '남한강 목계나루 인근의 36홀 잔디 구장',
    holesMetadata: generateStandardHoles(36),
  },
  {
    id: 'course-cheonan-pungse',
    name: '천안 풍세 파크골프장',
    region: '충남 천안시 동남구 풍세면',
    totalHoles: 18,
    isVerified: true,
    description: '풍서천 둔치에 위치한 18홀 코스',
    holesMetadata: generateStandardHoles(18),
  },
  {
    id: 'course-iksan-mangyeong',
    name: '익산 만경강 파크골프장',
    region: '전북 익산시 오산면',
    totalHoles: 36,
    isVerified: true,
    description: '만경강 하천부지에 넓게 펼쳐진 전북 대표 36홀 구장',
    holesMetadata: generateStandardHoles(36),
  },
  {
    id: 'course-hwacheon-sancheoneo',
    name: '화천 산천어 파크골프장',
    region: '강원 화천군 하남면',
    totalHoles: 36,
    isVerified: true,
    description: '북한강변 수려한 풍광을 자랑하는 36홀 공인 파크골프장',
    holesMetadata: generateStandardHoles(36),
  },
  {
    id: 'course-jeju-hoecheon',
    name: '제주 회천 파크골프장',
    region: '제주 제주시 회천동',
    totalHoles: 18,
    isVerified: true,
    description: '한라산 자락의 맑은 공기와 함께하는 제주 18홀 파크골프장',
    holesMetadata: generateStandardHoles(18),
  },
];

export const DISPUTE_RULES: DisputeRule[] = [
  // 1. OB 관련 규정
  {
    id: 'rule-ob-net-bounce',
    category: 'ob',
    title: '하얀 말뚝/그물망(안전망)을 맞고 코스 안으로 들어온 공',
    situation: '공이 하얀 OB 말뚝을 지나 외곽 그물망(네트)이나 나무를 맞고 다시 코스 안으로 튕겨 들어왔습니다.',
    verdict: '공의 최종 정지 위치가 코스 안이므로 【세이프(IN)】 무벌입니다.',
    penalty: '벌타 없음 (무벌)',
    procedure: '마지막에 어떤 형태로든 간에 OB선 밖으로 있지만 않으면 OB가 아닙니다. 멈춘 자리에서 그대로 다음 타를 진행합니다.',
    tags: ['OB', '그물망', '네트', '세이프', '무벌'],
    officialArticle: '제33조(아웃 오브 바운즈: OB 및 처치) 제2항',
    officialRuleText: '공이 OB 말뚝 또는 코스 밖의 장애물(안전망, 그물망, 펜스, 수목 등)을 맞고 다시 코스 안(인플레이 구역)으로 들어와 정지한 때에는 인플레이 볼로 본다(무벌).',
  },
  {
    id: 'rule-ob-line',
    category: 'ob',
    title: 'OB(아웃오브바운즈) 선 경계 판정 (선에 걸쳤을 때)',
    situation: '공이 OB 흰색 말뚝 선상에 아슬아슬하게 걸쳐 있을 때 세이프인가요, OB인가요?',
    verdict: '공의 일부라도 OB 선 안쪽에 닿아 있으면 【세이프(IN)】입니다.',
    penalty: '벌타 없음',
    procedure: '공의 직경 중 단 1mm라도 안쪽 잔디 경계선에 걸쳐있으면 정상 인플레이 볼입니다. 공 전체가 흰 선 밖으로 완전히 넘어가야만 OB 판정입니다.',
    tags: ['OB', '경계선', '말뚝', '세이프'],
    officialArticle: '제33조(아웃 오브 바운즈: OB 및 처치) 제1항',
    officialRuleText: '공 전체가 OB 선(또는 말뚝을 잇는 가상선)을 완전히 벗어나 정지했을 때 OB로 판정한다. 공의 직경 중 일부라도 코스 경계선 내에 접촉되어 있는 때에는 인플레이 구역의 공(세이프)으로 간주한다.',
  },
  {
    id: 'rule-ob-procedure',
    category: 'ob',
    title: 'OB 발생 시 벌타 및 다음 타 위치 처리',
    situation: '공이 완전히 OB 라인을 벗어나 나갔습니다. 몇 벌타를 받고 어디서 쳐야 하나요?',
    verdict: '【2벌타 가산】 후, OB 경계선을 넘은 지점에서 2클럽 이내에 놓고 플레이합니다.',
    penalty: '2벌타',
    procedure: '공이 OB 라인을 최종 통과한 지점을 기준으로, 홀컵에 가깝지 않게 코스 안쪽으로 2클럽 헤드 이내의 잔디에 공을 놓고 다음 타를 진행합니다. (구장 로컬룰에 OB 특설티가 있는 경우 특설티에서 진행)',
    tags: ['OB', '2벌타', '드롭', '2클럽'],
    officialArticle: '제33조(아웃 오브 바운즈: OB 및 처치) 제3항',
    officialRuleText: '공이 OB가 되었을 때에는 2벌타를 가산한다. 공이 OB 라인을 최종 통과한 지점을 기점으로 하여, 홀컵에 가깝지 않게 코스 안쪽으로 2클럽 이내에 공을 놓고 다음 타를 진행한다.',
  },
  {
    id: 'rule-ob-flag-bounce',
    category: 'ob',
    title: '깃대 맞고 튕겨 나가 OB가 된 경우',
    situation: '퍼팅한 공이 홀컵 깃대를 강하게 맞고 튕겨 나가 OB 라인 밖으로 나갔습니다.',
    verdict: '정상 샷의 결과로 보아 【2벌타 부여 후 OB 처치】합니다.',
    penalty: '2벌타',
    procedure: '깃대를 맞고 튕겨 나갔더라도 최종 공이 멈춘 위치가 OB 구역이므로 정규 OB 규정(2벌타)을 적용하여 OB 발생 지점에서 2클럽 이내 처치합니다.',
    tags: ['OB', '깃대', '2벌타'],
    officialArticle: '제33조(아웃 오브 바운즈: OB 및 처치) 제3항',
    officialRuleText: '공이 최종적으로 정지한 위치가 OB선 밖인 때에는 2벌타를 가산하고 공이 나간 경계선으로부터 2클럽 이내에서 처치한다.',
  },

  // 2. 해저드 / 벙커 관련 규정
  {
    id: 'rule-water-hazard',
    category: 'hazard',
    title: '워터 해저드(연못 / 개천)에 공이 빠졌을 때',
    situation: '친 공이 물이나 깊은 수로(해저드)에 빠져 칠 수 없습니다.',
    verdict: '【2벌타 가산】 후, 해저드 경계 진입 지점에서 2클럽 이내 처치합니다.',
    penalty: '2벌타',
    procedure: '공이 해저드 경계선을 최종 통과한 지점을 확인하고, 홀컵과 가깝지 않은 코스 내 2클럽 이내에 공을 놓고 다음 타를 칩니다.',
    tags: ['해저드', '물', '2벌타', '워터'],
    officialArticle: '제34조(워터 해저드 및 수리지) 제1항',
    officialRuleText: '공이 워터 해저드에 들어간 때에는 2벌타를 가산하고, 공이 해저드 경계선을 최종 통과한 지점에서 홀에 가깝지 않게 코스 내로 2클럽 이내에 놓고 플레이한다.',
  },
  {
    id: 'rule-casual-water',
    category: 'hazard',
    title: '비 온 뒤 잔디 웅덩이(캐주얼 워터 / 수리지)',
    situation: '비 온 뒤 잔디에 일시적으로 고인 물웅덩이나 잔디 보수 구역에 공이 멈췄습니다.',
    verdict: '비정상적인 코스 상태로 인정되어 【무벌 구제(1클럽 이내)】 가능합니다.',
    penalty: '벌타 없음 (무벌)',
    procedure: '물웅덩이를 피하여 홀컵에 더 가깝지 않은 가장 가까운 완전한 구제 지점을 정하고, 그 지점으로부터 1클럽 이내에 공을 놓고 플레이합니다.',
    tags: ['웅덩이', '수리지', '무벌', '구제'],
    officialArticle: '제34조(워터 해저드 및 수리지) 제2항',
    officialRuleText: '캐주얼 워터(일시적으로 고인 물) 또는 수리지 내에 공이 정지하거나 스탠스에 방해가 되는 경우, 홀에 가깝지 않은 구제 지점으로부터 1클럽 이내에 무벌로 공을 놓고 진행한다.',
  },
  {
    id: 'rule-bunker-sand',
    category: 'hazard',
    title: '벙커 안에서 어드레스 시 모래에 클럽이 닿았을 때',
    situation: '벙커에서 공을 치기 전 빈스윙을 하거나 클럽을 모래 바닥에 댔습니다.',
    verdict: '어드레스 시 가볍게 대는 것은 허용되나, 【모래를 누르거나 파헤치면 2벌타】입니다.',
    penalty: '고의 테스트 시 2벌타 (단순 터치는 무벌)',
    procedure: '파크골프 규정상 벙커 내에서 라이를 개선하거나 모래의 단단함을 테스트하기 위해 클럽으로 모래를 강하게 누르거나 쓸어내리면 2벌타가 부과됩니다.',
    tags: ['벙커', '모래', '라이개선'],
    officialArticle: '제38조(벙커 플레이)',
    officialRuleText: '벙커 안에서 어드레스 시 모래에 클럽 헤드를 가볍게 대는 행위는 허용된다. 단, 모래의 상태를 시험하거나 발 또는 클럽으로 모래를 누르거나 평탄하게 고르는 등 라이를 개선하는 행위는 2벌타를 부과한다.',
  },

  // 3. 기타 시설 / 장해물 관련 규정
  {
    id: 'rule-hazard-relief',
    category: 'facility',
    title: '배수구 / 안전망 / 스프링클러 무벌 구제',
    situation: '공이 인공 배수구 쇠창살 위나 안전 그물망, 쇠말뚝에 끼여 칠 수 없습니다.',
    verdict: '움직일 수 없는 인공 장해물로 인정되어 【무벌 구제(1클럽 이내)】가 가능합니다.',
    penalty: '벌타 없음 (무벌 구제)',
    procedure: '홀컵에 더 가깝지 않은 방향으로 공이 있던 지점에서 1클럽 헤드 이내의 잔디 위에 안전하게 공을 놓고 다음 샷을 이어갑니다.',
    tags: ['구제', '장해물', '배수구', '안전망'],
    officialArticle: '제35조(장해물) 제1항',
    officialRuleText: '움직일 수 없는 인공 장해물(스프링클러, 배수구, 안전망, 고정된 말뚝, 카트도로 등)이 스윙이나 스탠스에 방해를 줄 경우, 홀에 가깝지 않은 방향으로 1클럽 이내에 무벌로 공을 놓고 플레이한다.',
  },
  {
    id: 'rule-cart-road',
    category: 'facility',
    title: '포장된 카트 도로 / 보도블록 위에 공이 멈췄을 때',
    situation: '공이 아스팔트나 시멘트 카트 도로, 고무 매트 위에 멈췄습니다.',
    verdict: '인공 도로이므로 【무벌 구제(1클럽 이내 잔디 드롭)】 대상입니다.',
    penalty: '벌타 없음 (무벌)',
    procedure: '카트 도로를 벗어나 홀에 가깝지 않은 잔디 구역으로 1클럽 헤드 이내에 공을 놓고 샷을 합니다.',
    tags: ['카트도로', '포장도로', '무벌구제'],
    officialArticle: '제35조(장해물) 제1항',
    officialRuleText: '포장된 카트 도로 또는 인공 시설물 위에 공이 멈춘 때에는 무벌로 홀에 가깝지 않은 잔디 구역 1클럽 이내에 놓고 플레이한다.',
  },
  {
    id: 'rule-loose-impediment',
    category: 'facility',
    title: '공 주변 나뭇가지 / 마른 낙엽 / 돌멩이 치우기',
    situation: '공 바로 뒤에 부러진 나뭇가지나 마른 낙엽, 돌멩이가 있어 치우고 싶습니다.',
    verdict: '자연물(루스 임페디먼트)은 【벌타 없이 손으로 제거 가능】합니다.',
    penalty: '벌타 없음 (단, 공이 움직이면 1벌타)',
    procedure: '치우는 도중에 공이 움직이지 않도록 조심해야 합니다. 만약 나뭇가지를 치우다가 공이 건드려져 움직이면 1벌타가 가산되고 공은 원래 자리로 되돌려놓아야 합니다.',
    tags: ['나뭇가지', '돌멩이', '낙엽', '루스임페디먼트'],
    officialArticle: '제35조(장해물) 제2항',
    officialRuleText: '고정되지 않은 자연 장애물(낙엽, 떨어진 나뭇가지, 돌멩이 등)은 무벌로 치울 수 있다. 단, 이를 치우는 과정에서 정지된 공을 움직인 때에는 1벌타를 가산하고 원래 위치에 리플레이스한다.',
  },
  {
    id: 'rule-break-branch',
    category: 'facility',
    title: '살아있는 나무나 풀을 꺾거나 밟아서 치우는 행위',
    situation: '스윙 궤도에 걸리는 살아있는 나뭇가지를 꺾거나 발로 밟아 누르고 쳤습니다.',
    verdict: '라이 및 스윙 구역 개선 위반으로 【2벌타 부여】됩니다.',
    penalty: '2벌타',
    procedure: '성장하고 있는 자연물은 꺾거나 훼손할 수 없습니다. 있는 그대로의 상태에서 스윙을 해야 하며, 위반 시 2벌타가 부과됩니다.',
    tags: ['라이개선', '나무꺾기', '2벌타'],
    officialArticle: '제35조(장해물) 제3항',
    officialRuleText: '플레이어가 공의 상태나 스윙 구역, 플레이 선을 개선하기 위하여 살아있는 수목, 풀, 고정물을 꺾거나 구부리거나 발로 밟아 변형시키는 행위는 2벌타를 부과한다.',
  },

  // 4. 스윙 / 타수 / 기타 진행 규정
  {
    id: 'rule-miss-swing',
    category: 'swing',
    title: '헛스윙 시 타수 포함 여부',
    situation: '티샷이나 페어웨이에서 샷을 하려다 빗맞거나 바람만 가르고 공을 못 맞췄습니다.',
    verdict: '공을 치려는 의도(스윙)가 있었다면 【1타 가산】입니다.',
    penalty: '1타 가산 (벌타가 아닌 정상 스트로크 1회)',
    procedure: '단순 연습스윙(어드레스 풀기)이 아니라 공을 맞추려고 다운스윙을 시작했다면 공이 움직이지 않았더라도 1타를 친 것으로 인정됩니다. 다음 타수를 이어서 진행합니다.',
    tags: ['헛스윙', '타수', '스트로크', '의도'],
    officialArticle: '제30조(스트로크의 정의) 제2항',
    officialRuleText: '공을 타격하려는 의사를 가지고 다운스윙을 개시한 행위는 공을 헛맞추거나 맞추지 못하였더라도 1타의 스트로크로 간주한다. 단, 타격 의사가 없는 단순한 연습 스윙은 스트로크로 보지 않는다.',
  },
  {
    id: 'rule-ball-collision',
    category: 'swing',
    title: '동반자의 정지된 공을 맞췄을 때',
    situation: '내 공을 쳤는데 페어웨이나 그린에 서 있던 동반자의 공을 맞췄습니다.',
    verdict: '치는 사람에게는 【벌타 없음】, 맞은 동반자 공은 【원위치 리플레이스】입니다.',
    penalty: '벌타 없음 (무벌)',
    procedure: '맞고 튕겨나간 친 사람의 공은 멈춘 자리에 그대로 두고, 맞아서 움직인 동반자의 공은 원래 있던 자리로 다시 옮겨놓아야 합니다. (충돌 우려가 있을 때는 마크를 요청하세요)',
    tags: ['공 충돌', '마크', '무벌'],
    officialArticle: '제36조(공의 충돌 및 오구) 제1항',
    officialRuleText: '인플레이 볼이 코스 내에 정지되어 있는 다른 플레이어의 공을 맞힌 경우, 친 플레이어는 벌타가 없으며 공이 정지한 위치에서 플레이한다. 충돌로 움직인 다른 플레이어의 공은 원래 위치에 리플레이스한다.',
  },
  {
    id: 'rule-flagstick',
    category: 'swing',
    title: '깃대(깃발)를 맞고 튕겨 나온 공',
    situation: '퍼팅한 공이 홀컵에 꽂힌 깃대를 강하게 때리고 밖으로 튕겨 나갔습니다.',
    verdict: '홀에 들어가지 않았으므로 【홀아웃 불인정】, 멈춘 곳에서 다음 타 진행입니다.',
    penalty: '벌타 없음',
    procedure: '파크골프 규정상 깃대는 꽂힌 상태로 플레이하며, 깃대를 맞고 튕겨 나와 홀에 들어가지 않았다면 멈춘 위치에서 다음 스트로크를 진행해야 합니다.',
    tags: ['깃대', '홀컵', '퍼팅'],
    officialArticle: '제37조(홀아웃) 제2항',
    officialRuleText: '공 전체가 홀컵 바닥에 정지하였을 때 홀아웃으로 인정한다. 깃대를 맞고 튕겨 나와 홀컵 밖에 멈춘 공은 홀아웃으로 인정하지 않으며, 정지한 위치에서 무벌로 다음 스트로크를 진행한다.',
  },
  {
    id: 'rule-tee-fall',
    category: 'swing',
    title: '티샷 전 티에서 공이 저절로 굴러떨어졌을 때',
    situation: '티 위에 올려놓은 공이 스윙 시작 전 바람이나 실수로 살짝 건드려져 떨어졌습니다.',
    verdict: '스트로크 의도가 없었으므로 【벌타 없이 다시 티업】합니다.',
    penalty: '벌타 없음 (무벌)',
    procedure: '아직 샷을 하려는 다운스윙이 시작되기 전이므로 타수로 계산되지 않습니다. 벌타 없이 다시 티 위에 공을 올려놓고 침착하게 티샷을 시작합니다.',
    tags: ['티업', '티샷', '무벌'],
    officialArticle: '제30조(스트로크의 정의) 제4항',
    officialRuleText: '티잉그라운드에서 티업된 공이 스트로크(타격 의사 다운스윙)를 개시하기 전에 바람, 지면 흔들림, 가벼운 어드레스 터치 등으로 떨어진 때에는 스트로크로 보지 아니하며, 무벌로 다시 티업한다.',
  },
];

export const PRESCRIPTIONS = [
  {
    id: 'rx-par3-short',
    title: 'Par 3 쇼트홀 타수 누수 긴급 처방',
    summary: '숏퍼팅 거리감 및 헤드업 방지 공식',
    content: 'Par 3에서 타수가 늘어난 주요 원인은 1타 티샷 후 3~5m 퍼팅에서 홀컵을 지나치거나 짧은 경우입니다. 시선은 임팩트 후 1초간 잔디 바닥에 고정하고, 백스윙과 팔로우스루 비율을 1:1로 일정하게 유지하세요.',
  },
  {
    id: 'rx-ob-control',
    title: 'OB 다발 홀 방향성 보정 긴급 처방',
    summary: '헤드 릴리스와 어드레스 에이밍 재정렬',
    content: 'OB가 발생한 홀에서는 비거리를 의식해 몸이 먼저 열리는 현상이 발생합니다. 그립 악력을 30% 낮추고, 목표 지점보다 3m 앞의 잔디 티끌을 가상의 에이밍 포인트로 설정하여 부드럽게 스윙하세요.',
  },
  {
    id: 'rx-long-hole',
    title: 'Par 5 롱홀 세컨샷 안정성 처방',
    summary: '무리한 온그린 대신 30m 어프로치 분할 공략',
    content: '롱홀에서는 2온 욕심을 버리고 철저히 3온 전략을 취해야 안정적인 파(Par)를 세이브할 수 있습니다. 70m + 40m + 10m 구간별 타격 공식을 적용해 보세요.',
  },
];
